# Bibliografía {.unnumbered}

Corder, G. W., & Foreman, D. I. (2014). Nonparametric statistics: A step-by-step approach. John Wiley & Sons.

Deshpande, J. V., Naik-Nimbalkar, U., & Dewan, I. (2017). Nonparametric statistics: theory and methods. World Scientific.

Gomez Villegas, M. A. (2005). Inferencia estadística. Ediciones Díaz de Santos.

Bruce, P., Bruce, A., & Gedeck, P. (2020). Practical statistics for data scientists: 50+ essential concepts using R and Python. O’Reilly Media

Kelleher, J. D., & Tierney, B. (2018). Data science. MIT Press.

Ross, S. M. (2018). Introducción a la estadística. Reverté.

Wasserman, L. (2013). All of statistics: a concise course in statistical inference. Springer Science & Business Media.

Spiegel, M., & Stephens, L. (2009). Estadística–Serie Schaum. McGraw-Hill.

“Fundamentos de ciencia de datos con R” coordinado por Gema Fernández-Avilés y José-María Montero: https://cdr-book.github.io/

Weiss, N. A., & Weiss, C. A. (2017). Introductory statistics. London: Pearson.

“Estadística Aplicada a las Ciencias y la Ingeniería” escrito por Emilio L. Cano. https://emilopezcano.github.io/estadistica-ciencias-ingenieria/index.html

R for Data Science: https://r4ds.hadley.nz/eda Primera versión en castellano: https://es.r4ds.hadley.nz/

Bruce, P., Bruce, A., & Gedeck, P. (2020). Practical statistics for data scientists: 50+ essential concepts using R and Python. O’Reilly Media.

::: {#refs}
:::

