<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es-ES" xml:lang="es-ES"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.21">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Ingeniería de Características – Problemas de Modelos Estadísticos para la Predicción</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./tema4_seleccion_validacion_soluciones.html" rel="next">
<link href="./tema2_regresion_multiple_soluciones.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0687a6949ae11671cfb8b930681aab34.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="soluciones.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./tema3_ingenieria_caracteristicas_soluciones.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Ingeniería de Características</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Problemas de Modelos Estadísticos para la Predicción</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tema1_regresion_simple_soluciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regresión Lineal Simple</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tema2_regresion_multiple_soluciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regresión Lineal Múltiple</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tema3_ingenieria_caracteristicas_soluciones.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Ingeniería de Características</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tema4_seleccion_validacion_soluciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Selección de variables, Regularización y Validación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tema5_glm_soluciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelos de Regresión Generalizada</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ejercicios_avanzados_soluciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Ejercicios Avanzados</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#ejercicio-1-conceptual-diagnóstico-antes-de-transformar" id="toc-ejercicio-1-conceptual-diagnóstico-antes-de-transformar" class="nav-link active" data-scroll-target="#ejercicio-1-conceptual-diagnóstico-antes-de-transformar"><span class="header-section-number">3.1</span> Ejercicio 1: Conceptual (Diagnóstico antes de Transformar)</a></li>
  <li><a href="#ejercicio-2-práctico-escalado-de-variables" id="toc-ejercicio-2-práctico-escalado-de-variables" class="nav-link" data-scroll-target="#ejercicio-2-práctico-escalado-de-variables"><span class="header-section-number">3.2</span> Ejercicio 2: Práctico (Escalado de Variables)</a></li>
  <li><a href="#ejercicio-3-conceptual-elección-del-método-de-escalado" id="toc-ejercicio-3-conceptual-elección-del-método-de-escalado" class="nav-link" data-scroll-target="#ejercicio-3-conceptual-elección-del-método-de-escalado"><span class="header-section-number">3.3</span> Ejercicio 3: Conceptual (Elección del Método de Escalado)</a></li>
  <li><a href="#ejercicio-4-práctico-transformación-para-linealizar" id="toc-ejercicio-4-práctico-transformación-para-linealizar" class="nav-link" data-scroll-target="#ejercicio-4-práctico-transformación-para-linealizar"><span class="header-section-number">3.4</span> Ejercicio 4: Práctico (Transformación para Linealizar)</a></li>
  <li><a href="#ejercicio-5-práctico-transformación-de-box-cox" id="toc-ejercicio-5-práctico-transformación-de-box-cox" class="nav-link" data-scroll-target="#ejercicio-5-práctico-transformación-de-box-cox"><span class="header-section-number">3.5</span> Ejercicio 5: Práctico (Transformación de Box-Cox)</a></li>
  <li><a href="#ejercicio-6-conceptual-codificación-de-variables-categóricas" id="toc-ejercicio-6-conceptual-codificación-de-variables-categóricas" class="nav-link" data-scroll-target="#ejercicio-6-conceptual-codificación-de-variables-categóricas"><span class="header-section-number">3.6</span> Ejercicio 6: Conceptual (Codificación de Variables Categóricas)</a></li>
  <li><a href="#ejercicio-7-práctico-interacción-entre-variables-continuas" id="toc-ejercicio-7-práctico-interacción-entre-variables-continuas" class="nav-link" data-scroll-target="#ejercicio-7-práctico-interacción-entre-variables-continuas"><span class="header-section-number">3.7</span> Ejercicio 7: Práctico (Interacción entre Variables Continuas)</a></li>
  <li><a href="#ejercicio-8-interpretación-de-una-interacción-continua-x-categórica" id="toc-ejercicio-8-interpretación-de-una-interacción-continua-x-categórica" class="nav-link" data-scroll-target="#ejercicio-8-interpretación-de-una-interacción-continua-x-categórica"><span class="header-section-number">3.8</span> Ejercicio 8: Interpretación de una Interacción (Continua x Categórica)</a></li>
  <li><a href="#ejercicio-9-conceptual-principio-de-jerarquía" id="toc-ejercicio-9-conceptual-principio-de-jerarquía" class="nav-link" data-scroll-target="#ejercicio-9-conceptual-principio-de-jerarquía"><span class="header-section-number">3.9</span> Ejercicio 9: Conceptual (Principio de Jerarquía)</a></li>
  <li><a href="#ejercicio-10-conceptual-ingeniería-de-características-avanzada" id="toc-ejercicio-10-conceptual-ingeniería-de-características-avanzada" class="nav-link" data-scroll-target="#ejercicio-10-conceptual-ingeniería-de-características-avanzada"><span class="header-section-number">3.10</span> Ejercicio 10: Conceptual (Ingeniería de Características Avanzada)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Ingeniería de Características</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="ejercicio-1-conceptual-diagnóstico-antes-de-transformar" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="ejercicio-1-conceptual-diagnóstico-antes-de-transformar"><span class="header-section-number">3.1</span> Ejercicio 1: Conceptual (Diagnóstico antes de Transformar)</h2>
<p>El texto desaconseja fuertemente el enfoque de “ensayo y error” al aplicar transformaciones. Explica con tus propias palabras por qué la práctica de probar transformaciones hasta que mejore el R² es metodológicamente peligrosa. Menciona al menos tres de los riesgos específicos discutidos en los apuntes.</p>
<details>
<summary>
</summary>
<p>El enfoque de “ensayo y error” para transformaciones es metodológicamente peligroso por varios riesgos:</p>
<p><strong>1. Data snooping/p-hacking</strong>: Probar múltiples transformaciones hasta encontrar una que mejore el R² aumenta artificialmente la probabilidad de encontrar patrones espurios.</p>
<p><strong>2. Sobreajuste</strong>: El modelo resultante puede ajustarse específicamente a las peculiaridades de los datos de entrenamiento y no generalizar bien.</p>
<p><strong>3. Pérdida de interpretabilidad</strong>: Las transformaciones complejas pueden hacer que el modelo sea difícil de interpretar y comunicar.</p>
<p><strong>4. Invalidación de la inferencia estadística</strong>: Los p-valores y intervalos de confianza ya no son válidos cuando se ha hecho selección de modelos basada en los datos.</p>
<p><strong>5. Falta de justificación teórica</strong>: Sin una base conceptual, la transformación puede no tener sentido en el contexto del problema.</p>
</details>
</section>
<section id="ejercicio-2-práctico-escalado-de-variables" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="ejercicio-2-práctico-escalado-de-variables"><span class="header-section-number">3.2</span> Ejercicio 2: Práctico (Escalado de Variables)</h2>
<p>Utiliza el dataset <code>iris</code> de R y céntrate en las cuatro variables predictoras continuas (<code>Sepal.Length</code>, <code>Sepal.Width</code>, <code>Petal.Length</code>, <code>Petal.Width</code>).</p>
<ol type="a">
<li>Calcula la media y la desviación estándar de estas cuatro variables en su escala original. ¿Son sus escalas directamente comparables?</li>
<li>Crea un nuevo data frame donde hayas aplicado la <strong>estandarización Z-Score</strong> a estas cuatro variables. Verifica que las nuevas variables tienen una media cercana a 0 y una desviación estándar de 1.</li>
<li>¿Por qué este paso de escalado es crucial antes de aplicar métodos de regularización como Ridge o Lasso, tal y como se menciona en el texto?</li>
</ol>
<details>
<summary>
</summary>
<p><strong>a) Estadísticas descriptivas originales:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>variables_iris <span class="ot">&lt;-</span> iris[, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>estadisticas_orig <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Media =</span> <span class="fu">sapply</span>(variables_iris, mean),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Desv_Est =</span> <span class="fu">sapply</span>(variables_iris, sd)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Estadísticas originales:"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Estadísticas originales:"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(estadisticas_orig, <span class="dv">3</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Media Desv_Est
Sepal.Length 5.843    0.828
Sepal.Width  3.057    0.436
Petal.Length 3.758    1.765
Petal.Width  1.199    0.762</code></pre>
</div>
</div>
<p>Las escalas <strong>NO son directamente comparables</strong> porque tienen diferentes unidades y rangos de variación.</p>
<p><strong>b) Estandarización Z-Score:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>iris_scaled <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">scale</span>(variables_iris))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>estadisticas_scaled <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Media =</span> <span class="fu">sapply</span>(iris_scaled, mean),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Desv_Est =</span> <span class="fu">sapply</span>(iris_scaled, sd)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Estadísticas después de estandarización:"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Estadísticas después de estandarización:"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(estadisticas_scaled, <span class="dv">10</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Media Desv_Est
Sepal.Length     0        1
Sepal.Width      0        1
Petal.Length     0        1
Petal.Width      0        1</code></pre>
</div>
</div>
<p><strong>c) Importancia para regularización:</strong> El escalado es crucial para Ridge/Lasso porque estos métodos penalizan los coeficientes por su magnitud. Sin escalado, variables con escalas más grandes serían penalizadas más severamente, creando un sesgo artificial en la selección de variables.</p>
</details>
</section>
<section id="ejercicio-3-conceptual-elección-del-método-de-escalado" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="ejercicio-3-conceptual-elección-del-método-de-escalado"><span class="header-section-number">3.3</span> Ejercicio 3: Conceptual (Elección del Método de Escalado)</h2>
<p>Describe un escenario hipotético para cada uno de los siguientes casos, explicando por qué el método de escalado elegido sería el más apropiado:</p>
<ol type="a">
<li>Un escenario donde la <strong>estandarización Z-Score</strong> es preferible.</li>
<li>Un escenario donde la <strong>normalización Min-Max</strong> es preferible.</li>
<li>Un escenario donde el <strong>escalado robusto</strong> (usando mediana y IQR) es necesario.</li>
</ol>
<details>
<summary>
</summary>
<p><strong>a) Estandarización Z-Score preferible:</strong></p>
<ul>
<li><strong>Escenario</strong>: Análisis de datos de rendimiento académico donde las variables son notas de diferentes materias con distribuciones aproximadamente normales.</li>
<li><strong>Razón</strong>: Es el método estándar y funciona especialmente bien cuando las variables ya tienen una distribución aproximadamente simétrica o normal. Es la base de muchos procedimientos estadísticos que asumen este tipo de distribución.</li>
</ul>
<p><strong>b) Normalización Min-Max preferible:</strong></p>
<ul>
<li><strong>Escenario</strong>: Sistema de recomendación donde necesitas que todas las variables estén en el rango [0,1] para combinarlas en un score.</li>
<li><strong>Razón</strong>: Garantiza un rango específico y preserva las relaciones exactas entre valores.</li>
</ul>
<p><strong>c) Escalado robusto necesario:</strong></p>
<ul>
<li><strong>Escenario</strong>: Datos financieros con outliers extremos (como ingresos con algunos multimillonarios).</li>
<li><strong>Razón</strong>: La mediana y el IQR son menos sensibles a outliers que la media y desviación estándar.</li>
</ul>
</details>
</section>
<section id="ejercicio-4-práctico-transformación-para-linealizar" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="ejercicio-4-práctico-transformación-para-linealizar"><span class="header-section-number">3.4</span> Ejercicio 4: Práctico (Transformación para Linealizar)</h2>
<p>En el tema anterior vimos que la relación en el dataset <code>cars</code> (entre <code>speed</code> y <code>dist</code>) no era perfectamente lineal.</p>
<ol type="a">
<li>Ajusta el modelo <code>lm(dist ~ speed, data = cars)</code> y genera el gráfico de residuos vs.&nbsp;valores ajustados para confirmar visualmente la no linealidad (patrón curvo).</li>
<li>Los apuntes sugieren que la transformación logarítmica es útil para relaciones con “rendimientos decrecientes”. Propón y aplica una transformación (ej. sobre el predictor, la respuesta, o ambos) para intentar linealizar la relación. Por ejemplo, ajusta <code>lm(log(dist) ~ speed, data = cars)</code>.</li>
<li>Genera de nuevo el gráfico de residuos vs.&nbsp;valores ajustados para el nuevo modelo. Compara ambos diagnósticos. ¿Ha mejorado la linealidad?</li>
</ol>
<details>
<summary>
</summary>
<p><strong>a) Modelo original y diagnóstico:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>modelo_cars_orig <span class="ot">&lt;-</span> <span class="fu">lm</span>(dist <span class="sc">~</span> speed, <span class="at">data =</span> cars)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_cars_orig, <span class="at">which =</span> <span class="dv">1</span>, <span class="at">main =</span> <span class="st">"Modelo Original"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tema3_ingenieria_caracteristicas_soluciones_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>b) Transformación propuesta:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probamos transformación cuadrática del predictor</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>modelo_cars_trans <span class="ot">&lt;-</span> <span class="fu">lm</span>(dist <span class="sc">~</span> <span class="fu">I</span>(speed<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> cars)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_cars_trans, <span class="at">which =</span> <span class="dv">1</span>, <span class="at">main =</span> <span class="st">"Modelo Transformado"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tema3_ingenieria_caracteristicas_soluciones_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternativa: transformación logarítmica de la respuesta</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (eliminando dist = 0 si existe)</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>cars_filtered <span class="ot">&lt;-</span> cars[cars<span class="sc">$</span>dist <span class="sc">&gt;</span> <span class="dv">0</span>, ]</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>modelo_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(dist) <span class="sc">~</span> speed, <span class="at">data =</span> cars_filtered)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_log, <span class="at">which =</span> <span class="dv">1</span>, <span class="at">main =</span> <span class="st">"Modelo log(dist) ~ speed"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tema3_ingenieria_caracteristicas_soluciones_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>c) Evaluación:</strong> Sí, la linealidad ha mejorado notablemente con ambas transformaciones. Comparando los gráficos, tanto la transformación cuadrática del predictor como la logarítmica en la respuesta consiguen eliminar el patrón curvo de los residuos. La transformación logarítmica (<code>log(dist)</code>) parece producir una dispersión de residuos ligeramente más aleatoria y homogénea.</p>
</details>
</section>
<section id="ejercicio-5-práctico-transformación-de-box-cox" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="ejercicio-5-práctico-transformación-de-box-cox"><span class="header-section-number">3.5</span> Ejercicio 5: Práctico (Transformación de Box-Cox)</h2>
<p>Usa el dataset <code>Boston</code> de la librería <code>MASS</code>. La variable respuesta <code>medv</code> (valor mediano de la vivienda) es estrictamente positiva y tiene cierta asimetría.</p>
<ol type="a">
<li>Carga la librería <code>MASS</code> y utiliza la función <code>boxcox()</code> para encontrar el valor de <span class="math inline">\(\lambda\)</span> óptimo para la variable <code>medv</code> en un modelo simple frente a <code>lstat</code>. La fórmula sería <code>boxcox(medv ~ lstat, data = Boston)</code>.</li>
<li>Observando el gráfico que se genera, ¿a qué valor “simple” (como -1, 0, 0.5, 1) se aproxima el <span class="math inline">\(\lambda\)</span> óptimo?</li>
<li>Basándote en este resultado, ¿cuál de las transformaciones clásicas (logarítmica, raíz cuadrada, inversa, etc.) sería la más recomendable para la variable <code>medv</code>?</li>
</ol>
<details>
<summary>
</summary>
<p><strong>a) Análisis Box-Cox:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>modelo_boston <span class="ot">&lt;-</span> <span class="fu">lm</span>(medv <span class="sc">~</span> lstat, <span class="at">data =</span> Boston)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxcox</span>(modelo_boston)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tema3_ingenieria_caracteristicas_soluciones_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>b) Interpretación del gráfico:</strong> El λ óptimo parece estar cerca de <strong>λ = 0</strong>, lo que sugiere una <strong>transformación logarítmica</strong>.</p>
<p><strong>c) Recomendación:</strong> Basándose en λ ≈ 0, la transformación más recomendable sería <strong>log(medv)</strong>, que es la transformación logarítmica estándar.</p>
</details>
</section>
<section id="ejercicio-6-conceptual-codificación-de-variables-categóricas" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="ejercicio-6-conceptual-codificación-de-variables-categóricas"><span class="header-section-number">3.6</span> Ejercicio 6: Conceptual (Codificación de Variables Categóricas)</h2>
<p>Explica la diferencia fundamental entre la <strong>Codificación Ordinal</strong> y la <strong>Codificación One-Hot</strong>. Para cada una de las siguientes variables, indica qué método de codificación usarías y justifica tu elección:</p>
<ul>
<li><code>mes</code>: (“Enero”, “Febrero”, “Marzo”, …)</li>
<li><code>nivel_riesgo</code>: (“Bajo”, “Medio”, “Alto”, “Crítico”)</li>
<li><code>pais_origen</code>: (“España”, “Francia”, “Alemania”, “Italia”)</li>
</ul>
<details>
<summary>
</summary>
<p><strong>Diferencias fundamentales:</strong></p>
<ul>
<li><strong>Codificación Ordinal</strong>: Asigna números consecutivos preservando el orden (1, 2, 3, …)</li>
<li><strong>Codificación One-Hot</strong>: Crea variables binarias (0/1) para cada categoría</li>
</ul>
<p><strong>Recomendaciones:</strong></p>
<ul>
<li><p><strong>mes</strong>: <strong>One-Hot</strong> - Aunque tiene orden natural, los meses son cíclicos y la distancia entre Enero y Diciembre no es 11.</p></li>
<li><p><strong>nivel_riesgo</strong>: <strong>Ordinal</strong> - Hay una clara jerarquía natural (Bajo &lt; Medio &lt; Alto &lt; Crítico).</p></li>
<li><p><strong>pais_origen</strong>: <strong>One-Hot</strong> - No hay orden natural entre países, son categorías nominales.</p></li>
</ul>
</details>
</section>
<section id="ejercicio-7-práctico-interacción-entre-variables-continuas" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="ejercicio-7-práctico-interacción-entre-variables-continuas"><span class="header-section-number">3.7</span> Ejercicio 7: Práctico (Interacción entre Variables Continuas)</h2>
<p>Usa el dataset <code>mtcars</code> para investigar si el efecto del peso de un coche (<code>wt</code>) sobre su consumo (<code>mpg</code>) depende de su potencia (<code>hp</code>).</p>
<ol type="a">
<li>Ajusta un modelo que incluya un término de interacción entre <code>wt</code> y <code>hp</code>. Escribe la fórmula en R.</li>
<li>Observa el <code>summary()</code> del modelo. ¿Es el término de interacción (<code>wt:hp</code>) estadísticamente significativo a un nivel de <span class="math inline">\(\alpha = 0.05\)</span>?</li>
<li>Basándote en el signo del coeficiente de la interacción, ¿cómo cambia el efecto del peso sobre el consumo a medida que aumenta la potencia? (Es decir, ¿el efecto negativo del peso se hace más fuerte o más débil en los coches más potentes?).</li>
</ol>
<details>
<summary>
</summary>
<p><strong>a) Modelo con interacción:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>modelo_interaccion <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> hp <span class="sc">+</span> wt<span class="sc">:</span>hp, <span class="at">data =</span> mtcars)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># O equivalentemente: lm(mpg ~ wt * hp, data = mtcars)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>b) Summary del modelo:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_interaccion)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt + hp + wt:hp, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.0632 -1.6491 -0.7362  1.4211  4.5513 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 49.80842    3.60516  13.816 5.01e-14 ***
wt          -8.21662    1.26971  -6.471 5.20e-07 ***
hp          -0.12010    0.02470  -4.863 4.04e-05 ***
wt:hp        0.02785    0.00742   3.753 0.000811 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.153 on 28 degrees of freedom
Multiple R-squared:  0.8848,    Adjusted R-squared:  0.8724 
F-statistic: 71.66 on 3 and 28 DF,  p-value: 2.981e-13</code></pre>
</div>
</div>
<p><strong>b) Significancia de la interacción:</strong> El p-valor del término de interacción <code>wt:hp</code> es aproximadamente <strong>0.000811</strong>, que es mucho menor que 0.05, confirmando que la interacción es <strong>estadísticamente significativa</strong>.</p>
<p><strong>c) Interpretación del signo y la significancia:</strong></p>
<ol type="1">
<li><p><strong>Significancia:</strong> El p-valor del término de interacción <code>wt:hp</code> es <strong>0.000811</strong>, que es mucho menor que 0.05. Esto confirma que la interacción es <strong>estadísticamente significativa</strong>. El efecto del peso sobre el consumo realmente depende de la potencia del coche.</p></li>
<li><p><strong>Interpretación del Coeficiente:</strong> El coeficiente de la interacción <code>wt:hp</code> es <strong>positivo (+0.02785)</strong>. Esto significa que a medida que <code>hp</code> (potencia) aumenta, el efecto negativo de <code>wt</code> (peso) sobre <code>mpg</code> (consumo) se vuelve <strong>menos negativo (más débil)</strong>. En términos prácticos: el “castigo” al consumo por cada kilo extra de peso es menor en los coches que ya son muy potentes.</p></li>
</ol>
</details>
</section>
<section id="ejercicio-8-interpretación-de-una-interacción-continua-x-categórica" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="ejercicio-8-interpretación-de-una-interacción-continua-x-categórica"><span class="header-section-number">3.8</span> Ejercicio 8: Interpretación de una Interacción (Continua x Categórica)</h2>
<p>Un investigador modela el salario (<code>salario</code>, en euros) en función de los años de experiencia (<code>experiencia</code>) y si el empleado tiene o no un máster (<code>master</code>, con “No” como categoría de referencia). El modelo ajustado es:</p>
<p><code>salario = 30000 + 1200*experiencia + 8000*masterSi + 300*experiencia:masterSi</code></p>
<ol type="a">
<li>Escribe la ecuación de regresión específica para los empleados que <strong>no tienen</strong> un máster.</li>
<li>Escribe la ecuación de regresión específica para los empleados que <strong>sí tienen</strong> un máster.</li>
<li>Interpreta el coeficiente de la interacción (300). ¿Qué nos dice sobre el retorno económico de la experiencia para ambos grupos?</li>
</ol>
<details>
<summary>
</summary>
<p><strong>Modelo:</strong> <code>salario = 30000 + 1200*experiencia + 8000*masterSi + 300*experiencia:masterSi</code></p>
<p><strong>a) Ecuación para empleados SIN máster:</strong></p>
<pre><code>salario = 30000 + 1200*experiencia + 8000*(0) + 300*experiencia*(0)
salario = 30000 + 1200*experiencia</code></pre>
<p><strong>b) Ecuación para empleados CON máster:</strong></p>
<pre><code>salario = 30000 + 1200*experiencia + 8000*(1) + 300*experiencia*(1)
salario = 38000 + 1500*experiencia</code></pre>
<p><strong>c) Interpretación del coeficiente de interacción (300):</strong> El coeficiente de interacción indica que <strong>el retorno económico de cada año de experiencia es 300 euros mayor</strong> para los empleados con máster que para los empleados sin máster. Es decir, la experiencia es más valiosa económicamente para quienes tienen un máster.</p>
</details>
</section>
<section id="ejercicio-9-conceptual-principio-de-jerarquía" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="ejercicio-9-conceptual-principio-de-jerarquía"><span class="header-section-number">3.9</span> Ejercicio 9: Conceptual (Principio de Jerarquía)</h2>
<p>Explica el <strong>principio de jerarquía</strong> en el contexto de los modelos de regresión con interacciones. Si un modelo incluye el término de interacción <code>A:B</code>, ¿por qué es una buena práctica incluir siempre los efectos principales <code>A</code> y <code>B</code>, incluso si sus tests t individuales no son significativos?</p>
<details>
<summary>
</summary>
<p>El <strong>principio de jerarquía</strong> establece que si incluimos un término de interacción <code>A:B</code>, debemos incluir siempre los efectos principales <code>A</code> y <code>B</code>, incluso si no son individualmente significativos.</p>
<p><strong>Razones:</strong></p>
<ol type="1">
<li><p><strong>Interpretabilidad</strong>: Los términos de interacción representan desviaciones de los efectos principales. Sin los efectos principales, la interpretación se vuelve confusa.</p></li>
<li><p><strong>Estabilidad numérica</strong>: Los algoritmos de ajuste pueden volverse inestables sin los términos principales.</p></li>
<li><p><strong>Coherencia teórica</strong>: Desde una perspectiva conceptual, una interacción implica que existen efectos principales que se modifican mutuamente.</p></li>
</ol>
</details>
</section>
<section id="ejercicio-10-conceptual-ingeniería-de-características-avanzada" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="ejercicio-10-conceptual-ingeniería-de-características-avanzada"><span class="header-section-number">3.10</span> Ejercicio 10: Conceptual (Ingeniería de Características Avanzada)</h2>
<p>Los apuntes discuten la creación de nuevas variables mediante <strong>ratios</strong> y <strong>combinaciones</strong>. Para cada uno de los siguientes escenarios, propón una nueva variable (feature) que podrías crear y explica qué relación podría capturar mejor que las variables originales por sí solas.</p>
<ol type="a">
<li>Para predecir la rentabilidad de una tienda, tienes las variables <code>ventas_totales</code> y <code>numero_de_empleados</code>.</li>
<li>Para predecir el riesgo de impago de un solicitante de préstamo, tienes las variables <code>ingresos_anuales</code> y <code>deuda_total</code>.</li>
</ol>
<details>
<summary>
</summary>
<p><strong>a) Para predecir rentabilidad de tienda:</strong></p>
<ul>
<li><strong>Variable propuesta</strong>: <code>eficiencia_empleado = ventas_totales / numero_de_empleados</code></li>
<li><strong>Relación capturada</strong>: Productividad por empleado, que puede ser mejor predictor de rentabilidad que las variables por separado, ya que considera tanto el volumen de negocio como la eficiencia operativa.</li>
</ul>
<p><strong>b) Para predecir riesgo de impago:</strong></p>
<ul>
<li><strong>Variable propuesta</strong>: <code>ratio_deuda_ingresos = deuda_total / ingresos_anuales</code></li>
<li><strong>Relación capturada</strong>: Capacidad de pago relativa. Un ratio alto indica mayor riesgo independientemente de los valores absolutos. Por ejemplo, 50,000€ de deuda es muy diferente con ingresos de 30,000€ vs 100,000€.</li>
</ul>
</details>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./tema2_regresion_multiple_soluciones.html" class="pagination-link" aria-label="Regresión Lineal Múltiple">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regresión Lineal Múltiple</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./tema4_seleccion_validacion_soluciones.html" class="pagination-link" aria-label="Selección de variables, Regularización y Validación">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Selección de variables, Regularización y Validación</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>