<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; El modelo de regresión lineal múltiple – Modelos Estadísticos para la Predicción</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./tema3.html" rel="next">
<link href="./tema1.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1b90310288666db1f83ae9fc236520cd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./tema2.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">El modelo de regresión lineal múltiple</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Modelos Estadísticos para la Predicción</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tema0.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción a los modelos de regresión</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tema1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">El modelo de regresión lineal simple</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tema2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">El modelo de regresión lineal múltiple</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tema3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelos no lineales. Transformación de variables. Ingeniería de características.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tema4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelos de regresión generalizada</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tema5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Otros modelos de regresión: Modelos Aditivos Generalizados (GAMs)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Conclusiones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografía</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#sec-conceptos-fundamentales" id="toc-sec-conceptos-fundamentales" class="nav-link active" data-scroll-target="#sec-conceptos-fundamentales"><span class="header-section-number">3.1</span> Conceptos fundamentales</a>
  <ul class="collapse">
  <li><a href="#del-modelo-simple-al-múltiple-una-perspectiva-teórica" id="toc-del-modelo-simple-al-múltiple-una-perspectiva-teórica" class="nav-link" data-scroll-target="#del-modelo-simple-al-múltiple-una-perspectiva-teórica"><span class="header-section-number">3.1.1</span> Del modelo simple al múltiple: Una perspectiva teórica</a></li>
  <li><a href="#formulación-matricial-del-modelo" id="toc-formulación-matricial-del-modelo" class="nav-link" data-scroll-target="#formulación-matricial-del-modelo"><span class="header-section-number">3.1.2</span> Formulación matricial del modelo</a></li>
  <li><a href="#supuestos-fundamentales-del-modelo" id="toc-supuestos-fundamentales-del-modelo" class="nav-link" data-scroll-target="#supuestos-fundamentales-del-modelo"><span class="header-section-number">3.1.3</span> Supuestos fundamentales del modelo</a></li>
  <li><a href="#geometría-de-la-regresión-múltiple" id="toc-geometría-de-la-regresión-múltiple" class="nav-link" data-scroll-target="#geometría-de-la-regresión-múltiple"><span class="header-section-number">3.1.4</span> Geometría de la regresión múltiple</a></li>
  </ul></li>
  <li><a href="#sec-estimacion-parametros" id="toc-sec-estimacion-parametros" class="nav-link" data-scroll-target="#sec-estimacion-parametros"><span class="header-section-number">3.2</span> Estimación de parámetros</a>
  <ul class="collapse">
  <li><a href="#derivación-de-los-estimadores-de-mínimos-cuadrados" id="toc-derivación-de-los-estimadores-de-mínimos-cuadrados" class="nav-link" data-scroll-target="#derivación-de-los-estimadores-de-mínimos-cuadrados"><span class="header-section-number">3.2.1</span> Derivación de los estimadores de mínimos cuadrados</a></li>
  <li><a href="#propiedades-de-los-estimadores" id="toc-propiedades-de-los-estimadores" class="nav-link" data-scroll-target="#propiedades-de-los-estimadores"><span class="header-section-number">3.2.2</span> Propiedades de los estimadores</a></li>
  <li><a href="#estimación-de-la-varianza-del-error" id="toc-estimación-de-la-varianza-del-error" class="nav-link" data-scroll-target="#estimación-de-la-varianza-del-error"><span class="header-section-number">3.2.3</span> Estimación de la varianza del error</a></li>
  <li><a href="#interpretación-de-coeficientes-en-regresión-múltiple" id="toc-interpretación-de-coeficientes-en-regresión-múltiple" class="nav-link" data-scroll-target="#interpretación-de-coeficientes-en-regresión-múltiple"><span class="header-section-number">3.2.4</span> Interpretación de coeficientes en regresión múltiple</a></li>
  <li><a href="#propiedades-de-los-residuos-y-valores-ajustados" id="toc-propiedades-de-los-residuos-y-valores-ajustados" class="nav-link" data-scroll-target="#propiedades-de-los-residuos-y-valores-ajustados"><span class="header-section-number">3.2.5</span> Propiedades de los residuos y valores ajustados</a></li>
  <li><a href="#inferencia-estadística" id="toc-inferencia-estadística" class="nav-link" data-scroll-target="#inferencia-estadística"><span class="header-section-number">3.2.6</span> Inferencia estadística</a></li>
  </ul></li>
  <li><a href="#sec-ejemplo-practico" id="toc-sec-ejemplo-practico" class="nav-link" data-scroll-target="#sec-ejemplo-practico"><span class="header-section-number">3.3</span> Ejemplo práctico: Datos de viviendas</a>
  <ul class="collapse">
  <li><a href="#modelo-múltiple-inicial" id="toc-modelo-múltiple-inicial" class="nav-link" data-scroll-target="#modelo-múltiple-inicial"><span class="header-section-number">3.3.1</span> Modelo múltiple inicial</a></li>
  <li><a href="#interpretación-de-coeficientes" id="toc-interpretación-de-coeficientes" class="nav-link" data-scroll-target="#interpretación-de-coeficientes"><span class="header-section-number">3.3.2</span> Interpretación de coeficientes</a></li>
  </ul></li>
  <li><a href="#sec-transformaciones-variables" id="toc-sec-transformaciones-variables" class="nav-link" data-scroll-target="#sec-transformaciones-variables"><span class="header-section-number">3.4</span> Transformaciones de variables</a>
  <ul class="collapse">
  <li><a href="#transformación-logarítmica" id="toc-transformación-logarítmica" class="nav-link" data-scroll-target="#transformación-logarítmica"><span class="header-section-number">3.4.1</span> Transformación logarítmica</a></li>
  <li><a href="#transformación-polinomial" id="toc-transformación-polinomial" class="nav-link" data-scroll-target="#transformación-polinomial"><span class="header-section-number">3.4.2</span> Transformación polinomial</a></li>
  <li><a href="#transformación-de-variables-predictoras" id="toc-transformación-de-variables-predictoras" class="nav-link" data-scroll-target="#transformación-de-variables-predictoras"><span class="header-section-number">3.4.3</span> Transformación de variables predictoras</a></li>
  </ul></li>
  <li><a href="#sec-interacciones" id="toc-sec-interacciones" class="nav-link" data-scroll-target="#sec-interacciones"><span class="header-section-number">3.5</span> Interacciones entre variables</a>
  <ul class="collapse">
  <li><a href="#concepto-de-interacción" id="toc-concepto-de-interacción" class="nav-link" data-scroll-target="#concepto-de-interacción"><span class="header-section-number">3.5.1</span> Concepto de interacción</a></li>
  <li><a href="#interacción-entre-variables-continuas" id="toc-interacción-entre-variables-continuas" class="nav-link" data-scroll-target="#interacción-entre-variables-continuas"><span class="header-section-number">3.5.2</span> Interacción entre variables continuas</a></li>
  <li><a href="#interacción-entre-variable-continua-y-categórica" id="toc-interacción-entre-variable-continua-y-categórica" class="nav-link" data-scroll-target="#interacción-entre-variable-continua-y-categórica"><span class="header-section-number">3.5.3</span> Interacción entre variable continua y categórica</a></li>
  <li><a href="#interpretación-de-interacciones" id="toc-interpretación-de-interacciones" class="nav-link" data-scroll-target="#interpretación-de-interacciones"><span class="header-section-number">3.5.4</span> Interpretación de interacciones</a></li>
  </ul></li>
  <li><a href="#sec-diagnostico-multiple" id="toc-sec-diagnostico-multiple" class="nav-link" data-scroll-target="#sec-diagnostico-multiple"><span class="header-section-number">3.6</span> Diagnóstico del modelo múltiple</a>
  <ul class="collapse">
  <li><a href="#gráficos-de-residuos-parciales" id="toc-gráficos-de-residuos-parciales" class="nav-link" data-scroll-target="#gráficos-de-residuos-parciales"><span class="header-section-number">3.6.1</span> Gráficos de residuos parciales</a></li>
  <li><a href="#gráficos-de-residuos-vs-predictores" id="toc-gráficos-de-residuos-vs-predictores" class="nav-link" data-scroll-target="#gráficos-de-residuos-vs-predictores"><span class="header-section-number">3.6.2</span> Gráficos de residuos vs predictores</a></li>
  <li><a href="#pruebas-estadísticas-específicas" id="toc-pruebas-estadísticas-específicas" class="nav-link" data-scroll-target="#pruebas-estadísticas-específicas"><span class="header-section-number">3.6.3</span> Pruebas estadísticas específicas</a></li>
  </ul></li>
  <li><a href="#sec-multicolinealidad" id="toc-sec-multicolinealidad" class="nav-link" data-scroll-target="#sec-multicolinealidad"><span class="header-section-number">3.7</span> Multicolinealidad</a>
  <ul class="collapse">
  <li><a href="#qué-es-la-multicolinealidad" id="toc-qué-es-la-multicolinealidad" class="nav-link" data-scroll-target="#qué-es-la-multicolinealidad"><span class="header-section-number">3.7.1</span> ¿Qué es la multicolinealidad?</a></li>
  <li><a href="#consecuencias-de-la-multicolinealidad" id="toc-consecuencias-de-la-multicolinealidad" class="nav-link" data-scroll-target="#consecuencias-de-la-multicolinealidad"><span class="header-section-number">3.7.2</span> Consecuencias de la multicolinealidad</a></li>
  <li><a href="#detección-factor-de-inflación-de-varianza-vif" id="toc-detección-factor-de-inflación-de-varianza-vif" class="nav-link" data-scroll-target="#detección-factor-de-inflación-de-varianza-vif"><span class="header-section-number">3.7.3</span> Detección: Factor de Inflación de Varianza (VIF)</a></li>
  <li><a href="#ejemplo-de-multicolinealidad-alta" id="toc-ejemplo-de-multicolinealidad-alta" class="nav-link" data-scroll-target="#ejemplo-de-multicolinealidad-alta"><span class="header-section-number">3.7.4</span> Ejemplo de multicolinealidad alta</a></li>
  <li><a href="#soluciones-para-la-multicolinealidad" id="toc-soluciones-para-la-multicolinealidad" class="nav-link" data-scroll-target="#soluciones-para-la-multicolinealidad"><span class="header-section-number">3.7.5</span> Soluciones para la multicolinealidad</a></li>
  </ul></li>
  <li><a href="#sec-evaluacion-modelos" id="toc-sec-evaluacion-modelos" class="nav-link" data-scroll-target="#sec-evaluacion-modelos"><span class="header-section-number">3.8</span> Evaluación y comparación de modelos</a>
  <ul class="collapse">
  <li><a href="#criterios-de-información" id="toc-criterios-de-información" class="nav-link" data-scroll-target="#criterios-de-información"><span class="header-section-number">3.8.1</span> Criterios de información</a></li>
  <li><a href="#validación-cruzada" id="toc-validación-cruzada" class="nav-link" data-scroll-target="#validación-cruzada"><span class="header-section-number">3.8.2</span> Validación cruzada</a></li>
  </ul></li>
  <li><a href="#sec-casos-especiales" id="toc-sec-casos-especiales" class="nav-link" data-scroll-target="#sec-casos-especiales"><span class="header-section-number">3.9</span> Análisis de casos especiales</a>
  <ul class="collapse">
  <li><a href="#variables-categóricas-con-múltiples-niveles" id="toc-variables-categóricas-con-múltiples-niveles" class="nav-link" data-scroll-target="#variables-categóricas-con-múltiples-niveles"><span class="header-section-number">3.9.1</span> Variables categóricas con múltiples niveles</a></li>
  <li><a href="#análisis-de-outliers-en-regresión-múltiple" id="toc-análisis-de-outliers-en-regresión-múltiple" class="nav-link" data-scroll-target="#análisis-de-outliers-en-regresión-múltiple"><span class="header-section-number">3.9.2</span> Análisis de outliers en regresión múltiple</a></li>
  </ul></li>
  <li><a href="#sec-ejemplo-completo" id="toc-sec-ejemplo-completo" class="nav-link" data-scroll-target="#sec-ejemplo-completo"><span class="header-section-number">3.10</span> Ejemplo completo: Análisis paso a paso</a></li>
  <li><a href="#sec-conclusiones" id="toc-sec-conclusiones" class="nav-link" data-scroll-target="#sec-conclusiones"><span class="header-section-number">3.11</span> Conclusiones y recomendaciones prácticas</a>
  <ul class="collapse">
  <li><a href="#puntos-clave-de-la-regresión-múltiple" id="toc-puntos-clave-de-la-regresión-múltiple" class="nav-link" data-scroll-target="#puntos-clave-de-la-regresión-múltiple"><span class="header-section-number">3.11.1</span> Puntos clave de la regresión múltiple</a></li>
  <li><a href="#flujo-de-trabajo-recomendado" id="toc-flujo-de-trabajo-recomendado" class="nav-link" data-scroll-target="#flujo-de-trabajo-recomendado"><span class="header-section-number">3.11.2</span> Flujo de trabajo recomendado</a></li>
  <li><a href="#preparación-para-temas-avanzados" id="toc-preparación-para-temas-avanzados" class="nav-link" data-scroll-target="#preparación-para-temas-avanzados"><span class="header-section-number">3.11.3</span> Preparación para temas avanzados</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-regresion-lineal-multiple" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">El modelo de regresión lineal múltiple</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>El modelo de regresión lineal múltiple constituye la extensión natural y más potente del modelo simple que estudiamos en el capítulo anterior. Mientras que la regresión simple nos permitía examinar la relación entre una variable respuesta y un único predictor, la regresión múltiple nos capacita para <strong>modelar simultáneamente el efecto de múltiples variables predictoras</strong>, una situación mucho más realista en la mayoría de aplicaciones prácticas <span class="citation" data-cites="kutner2005applied james2021 fox2018r">(<a href="references.html#ref-kutner2005applied" role="doc-biblioref">Kutner et&nbsp;al. 2005</a>; <a href="references.html#ref-james2021" role="doc-biblioref">James et&nbsp;al. 2021</a>; <a href="references.html#ref-fox2018r" role="doc-biblioref">Fox y Weisberg 2018</a>)</span>.</p>
<p>En este capítulo profundizaremos en los aspectos únicos de la regresión múltiple que no están presentes en el caso simple: la <strong>interpretación de coeficientes en presencia de otros predictores</strong>, las <strong>transformaciones de variables</strong> para capturar relaciones no lineales, las <strong>interacciones</strong> entre variables, el <strong>diagnóstico específico</strong> del modelo múltiple, y el problema crucial de la <strong>multicolinealidad</strong>. Estos conceptos son fundamentales para desarrollar modelos predictivos robustos y interpretables <span class="citation" data-cites="harrell2015 draper1998applied">(<a href="references.html#ref-harrell2015" role="doc-biblioref">Harrell 2015</a>; <a href="references.html#ref-draper1998applied" role="doc-biblioref">Draper 1998</a>)</span>.</p>
<p>La comprensión sólida de estos principios es esencial, ya que constituyen la base conceptual sobre la que se construyen técnicas más avanzadas como la selección de variables (Tema 3), los modelos lineales generalizados (Tema 4), y las tendencias modernas en modelado estadístico (Tema 5).</p>
<div class="callout callout-style-default callout-important callout-titled" title="Objetivos de aprendizaje">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Objetivos de aprendizaje
</div>
</div>
<div class="callout-body-container callout-body">
<p>Al finalizar este capítulo, serás capaz de:</p>
<ol type="1">
<li><strong>Formular y estimar</strong> modelos de regresión lineal múltiple, comprendiendo las diferencias clave respecto al caso simple.</li>
<li><strong>Interpretar coeficientes</strong> en el contexto multivariante, entendiendo el concepto de “manteniendo las demás variables constantes”.</li>
<li><strong>Aplicar transformaciones de variables</strong> para capturar relaciones no lineales y mejorar el ajuste del modelo.</li>
<li><strong>Modelar e interpretar interacciones</strong> entre variables predictoras y entender cuándo son necesarias.</li>
<li><strong>Diagnosticar el modelo múltiple</strong>, aplicando técnicas específicas para detectar problemas únicos del caso multivariante.</li>
<li><strong>Identificar y tratar la multicolinealidad</strong>, comprendiendo sus causas, consecuencias y soluciones.</li>
<li><strong>Evaluar y comparar modelos múltiples</strong> usando criterios apropiados para la selección del mejor modelo.</li>
</ol>
</div>
</div>
<section id="sec-conceptos-fundamentales" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-conceptos-fundamentales"><span class="header-section-number">3.1</span> Conceptos fundamentales</h2>
<section id="del-modelo-simple-al-múltiple-una-perspectiva-teórica" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="del-modelo-simple-al-múltiple-una-perspectiva-teórica"><span class="header-section-number">3.1.1</span> Del modelo simple al múltiple: Una perspectiva teórica</h3>
<p>El modelo de regresión lineal múltiple representa una extensión natural pero conceptualmente rica del modelo simple. Para <span class="math inline">\(n\)</span> observaciones y <span class="math inline">\(p\)</span> variables predictoras, el modelo se expresa como:</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 X_{i1} + \beta_2 X_{i2} + ... + \beta_p X_{ip} + \varepsilon_i, \quad i = 1, 2, ..., n\]</span></p>
<p>donde: - <span class="math inline">\(Y_i\)</span> es la <span class="math inline">\(i\)</span>-ésima observación de la variable respuesta - <span class="math inline">\(X_{ij}\)</span> es la <span class="math inline">\(i\)</span>-ésima observación de la <span class="math inline">\(j\)</span>-ésima variable predictora - <span class="math inline">\(\beta_0, \beta_1, ..., \beta_p\)</span> son los parámetros del modelo - <span class="math inline">\(\varepsilon_i\)</span> es el término de error para la <span class="math inline">\(i\)</span>-ésima observación</p>
</section>
<section id="formulación-matricial-del-modelo" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="formulación-matricial-del-modelo"><span class="header-section-number">3.1.2</span> Formulación matricial del modelo</h3>
<p>La representación matricial es fundamental para el desarrollo teórico:</p>
<p><span class="math display">\[\mathbf{y} = \mathbf{X}\boldsymbol{\beta} + \boldsymbol{\varepsilon}\]</span></p>
<p>donde:</p>
<p><span class="math display">\[\mathbf{y} = \begin{bmatrix} Y_1 \\ Y_2 \\ \vdots \\ Y_n \end{bmatrix}, \quad
\mathbf{X} = \begin{bmatrix}
1 &amp; X_{11} &amp; X_{12} &amp; \cdots &amp; X_{1p} \\
1 &amp; X_{21} &amp; X_{22} &amp; \cdots &amp; X_{2p} \\
\vdots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
1 &amp; X_{n1} &amp; X_{n2} &amp; \cdots &amp; X_{np}
\end{bmatrix}\]</span></p>
<p><span class="math display">\[\boldsymbol{\beta} = \begin{bmatrix} \beta_0 \\ \beta_1 \\ \vdots \\ \beta_p \end{bmatrix}, \quad
\boldsymbol{\varepsilon} = \begin{bmatrix} \varepsilon_1 \\ \varepsilon_2 \\ \vdots \\ \varepsilon_n \end{bmatrix}\]</span></p>
<p>La matriz <span class="math inline">\(\mathbf{X}\)</span> es de dimensión <span class="math inline">\(n \times (p+1)\)</span> y se denomina <strong>matriz de diseño</strong>.</p>
</section>
<section id="supuestos-fundamentales-del-modelo" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="supuestos-fundamentales-del-modelo"><span class="header-section-number">3.1.3</span> Supuestos fundamentales del modelo</h3>
<p>Los supuestos del modelo de regresión lineal múltiple, conocidos como <strong>condiciones de Gauss-Markov</strong>, son:</p>
<section id="supuesto-1-linealidad" class="level4" data-number="3.1.3.1">
<h4 data-number="3.1.3.1" class="anchored" data-anchor-id="supuesto-1-linealidad"><span class="header-section-number">3.1.3.1</span> <strong>Supuesto 1: Linealidad</strong></h4>
<p><span class="math display">\[E[\mathbf{y}|\mathbf{X}] = \mathbf{X}\boldsymbol{\beta}\]</span></p>
<p>La esperanza condicional de <span class="math inline">\(\mathbf{y}\)</span> es una función lineal de los parámetros <span class="math inline">\(\boldsymbol{\beta}\)</span>.</p>
</section>
<section id="supuesto-2-independencia" class="level4" data-number="3.1.3.2">
<h4 data-number="3.1.3.2" class="anchored" data-anchor-id="supuesto-2-independencia"><span class="header-section-number">3.1.3.2</span> <strong>Supuesto 2: Independencia</strong></h4>
<p><span class="math display">\[E[\varepsilon_i \varepsilon_j] = 0, \quad \forall i \neq j\]</span></p>
<p>Los errores son no correlacionados entre observaciones.</p>
</section>
<section id="supuesto-3-homocedasticidad" class="level4" data-number="3.1.3.3">
<h4 data-number="3.1.3.3" class="anchored" data-anchor-id="supuesto-3-homocedasticidad"><span class="header-section-number">3.1.3.3</span> <strong>Supuesto 3: Homocedasticidad</strong></h4>
<p><span class="math display">\[\text{Var}(\varepsilon_i) = \sigma^2, \quad \forall i = 1, 2, ..., n\]</span></p>
<p>La varianza del error es constante para todas las observaciones.</p>
</section>
<section id="supuesto-4-media-nula" class="level4" data-number="3.1.3.4">
<h4 data-number="3.1.3.4" class="anchored" data-anchor-id="supuesto-4-media-nula"><span class="header-section-number">3.1.3.4</span> <strong>Supuesto 4: Media nula</strong></h4>
<p><span class="math display">\[E[\varepsilon_i] = 0, \quad \forall i = 1, 2, ..., n\]</span></p>
<p>Los errores tienen esperanza cero.</p>
</section>
<section id="supuesto-5-rango-completo" class="level4" data-number="3.1.3.5">
<h4 data-number="3.1.3.5" class="anchored" data-anchor-id="supuesto-5-rango-completo"><span class="header-section-number">3.1.3.5</span> <strong>Supuesto 5: Rango completo</strong></h4>
<p><span class="math display">\[\text{rango}(\mathbf{X}) = p + 1 &lt; n\]</span></p>
<p>La matriz <span class="math inline">\(\mathbf{X}\)</span> tiene rango completo (no hay multicolinealidad perfecta).</p>
<p><strong>Formulación matricial conjunta:</strong> <span class="math display">\[E[\boldsymbol{\varepsilon}] = \mathbf{0}, \quad \text{Var}(\boldsymbol{\varepsilon}) = \sigma^2 \mathbf{I}_n\]</span></p>
</section>
<section id="supuesto-adicional-para-inferencia" class="level4" data-number="3.1.3.6">
<h4 data-number="3.1.3.6" class="anchored" data-anchor-id="supuesto-adicional-para-inferencia"><span class="header-section-number">3.1.3.6</span> <strong>Supuesto adicional para inferencia:</strong></h4>
<p><strong>Normalidad</strong>: <span class="math display">\[\boldsymbol{\varepsilon} \sim N(\mathbf{0}, \sigma^2 \mathbf{I}_n)\]</span></p>
<p>Este supuesto no es necesario para las propiedades BLUE de los estimadores, pero sí para la inferencia estadística exacta.</p>
</section>
</section>
<section id="geometría-de-la-regresión-múltiple" class="level3" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="geometría-de-la-regresión-múltiple"><span class="header-section-number">3.1.4</span> Geometría de la regresión múltiple</h3>
<section id="espacios-vectoriales" class="level4" data-number="3.1.4.1">
<h4 data-number="3.1.4.1" class="anchored" data-anchor-id="espacios-vectoriales"><span class="header-section-number">3.1.4.1</span> <strong>Espacios vectoriales</strong></h4>
<p>En regresión múltiple, trabajamos en el espacio <span class="math inline">\(\mathbb{R}^n\)</span>:</p>
<ul>
<li>El vector de observaciones <span class="math inline">\(\mathbf{y} \in \mathbb{R}^n\)</span></li>
<li>Cada columna de <span class="math inline">\(\mathbf{X}\)</span> (incluyendo el vector de unos) genera un subespacio</li>
<li>El <strong>espacio columna</strong> de <span class="math inline">\(\mathbf{X}\)</span>, denotado <span class="math inline">\(C(\mathbf{X})\)</span>, es el subespacio generado por las columnas de <span class="math inline">\(\mathbf{X}\)</span></li>
</ul>
</section>
<section id="proyección-ortogonal" class="level4" data-number="3.1.4.2">
<h4 data-number="3.1.4.2" class="anchored" data-anchor-id="proyección-ortogonal"><span class="header-section-number">3.1.4.2</span> <strong>Proyección ortogonal</strong></h4>
<p>El vector de valores ajustados <span class="math inline">\(\hat{\mathbf{y}} = \mathbf{X}\hat{\boldsymbol{\beta}}\)</span> es la <strong>proyección ortogonal</strong> de <span class="math inline">\(\mathbf{y}\)</span> sobre <span class="math inline">\(C(\mathbf{X})\)</span>:</p>
<p><span class="math display">\[\hat{\mathbf{y}} = \text{Proj}_{C(\mathbf{X})} \mathbf{y}\]</span></p>
<p>La matriz de proyección es: <span class="math display">\[\mathbf{H} = \mathbf{X}(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\]</span></p>
<p>con las propiedades: - <span class="math inline">\(\mathbf{H}\mathbf{H} = \mathbf{H}\)</span> (idempotente) - <span class="math inline">\(\mathbf{H}^T = \mathbf{H}\)</span> (simétrica) - <span class="math inline">\(\text{traza}(\mathbf{H}) = p + 1\)</span> (número de parámetros)</p>
</section>
<section id="descomposición-ortogonal" class="level4" data-number="3.1.4.3">
<h4 data-number="3.1.4.3" class="anchored" data-anchor-id="descomposición-ortogonal"><span class="header-section-number">3.1.4.3</span> <strong>Descomposición ortogonal</strong></h4>
<p><span class="math display">\[\mathbf{y} = \hat{\mathbf{y}} + \mathbf{e} = \mathbf{H}\mathbf{y} + (\mathbf{I}_n - \mathbf{H})\mathbf{y}\]</span></p>
<p>donde <span class="math inline">\(\mathbf{e} = \mathbf{y} - \hat{\mathbf{y}}\)</span> es el vector de residuos, y se cumple:</p>
<p><span class="math display">\[\hat{\mathbf{y}}^T \mathbf{e} = 0\]</span></p>
<p>Esta ortogonalidad es fundamental para el Teorema de Pitágoras en regresión.</p>
</section>
</section>
</section>
<section id="sec-estimacion-parametros" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-estimacion-parametros"><span class="header-section-number">3.2</span> Estimación de parámetros</h2>
<section id="derivación-de-los-estimadores-de-mínimos-cuadrados" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="derivación-de-los-estimadores-de-mínimos-cuadrados"><span class="header-section-number">3.2.1</span> Derivación de los estimadores de mínimos cuadrados</h3>
<section id="función-objetivo" class="level4" data-number="3.2.1.1">
<h4 data-number="3.2.1.1" class="anchored" data-anchor-id="función-objetivo"><span class="header-section-number">3.2.1.1</span> <strong>Función objetivo</strong></h4>
<p>Buscamos minimizar la suma de cuadrados de errores:</p>
<p><span class="math display">\[SSE(\boldsymbol{\beta}) = \sum_{i=1}^n (Y_i - \beta_0 - \beta_1 X_{i1} - ... - \beta_p X_{ip})^2\]</span></p>
<p>En notación matricial: <span class="math display">\[SSE(\boldsymbol{\beta}) = (\mathbf{y} - \mathbf{X}\boldsymbol{\beta})^T(\mathbf{y} - \mathbf{X}\boldsymbol{\beta})\]</span></p>
</section>
<section id="desarrollo-de-la-función-objetivo" class="level4" data-number="3.2.1.2">
<h4 data-number="3.2.1.2" class="anchored" data-anchor-id="desarrollo-de-la-función-objetivo"><span class="header-section-number">3.2.1.2</span> <strong>Desarrollo de la función objetivo</strong></h4>
<p>Expandiendo: <span class="math display">\[\begin{align}
SSE(\boldsymbol{\beta}) &amp;= \mathbf{y}^T\mathbf{y} - \boldsymbol{\beta}^T\mathbf{X}^T\mathbf{y} - \mathbf{y}^T\mathbf{X}\boldsymbol{\beta} + \boldsymbol{\beta}^T\mathbf{X}^T\mathbf{X}\boldsymbol{\beta}\\
&amp;= \mathbf{y}^T\mathbf{y} - 2\boldsymbol{\beta}^T\mathbf{X}^T\mathbf{y} + \boldsymbol{\beta}^T\mathbf{X}^T\mathbf{X}\boldsymbol{\beta}
\end{align}\]</span></p>
</section>
<section id="condiciones-de-primer-orden" class="level4" data-number="3.2.1.3">
<h4 data-number="3.2.1.3" class="anchored" data-anchor-id="condiciones-de-primer-orden"><span class="header-section-number">3.2.1.3</span> <strong>Condiciones de primer orden</strong></h4>
<p>Derivando respecto a <span class="math inline">\(\boldsymbol{\beta}\)</span> e igualando a cero:</p>
<p><span class="math display">\[\frac{\partial SSE}{\partial \boldsymbol{\beta}} = -2\mathbf{X}^T\mathbf{y} + 2\mathbf{X}^T\mathbf{X}\boldsymbol{\beta} = \mathbf{0}\]</span></p>
</section>
<section id="ecuaciones-normales" class="level4" data-number="3.2.1.4">
<h4 data-number="3.2.1.4" class="anchored" data-anchor-id="ecuaciones-normales"><span class="header-section-number">3.2.1.4</span> <strong>Ecuaciones normales</strong></h4>
<p><span class="math display">\[\mathbf{X}^T\mathbf{X}\hat{\boldsymbol{\beta}} = \mathbf{X}^T\mathbf{y}\]</span></p>
<p>Si <span class="math inline">\(\mathbf{X}^T\mathbf{X}\)</span> es no singular (rango completo), la solución única es:</p>
<p><span class="math display">\[\boxed{\hat{\boldsymbol{\beta}} = (\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{y}}\]</span></p>
</section>
<section id="condiciones-de-segundo-orden" class="level4" data-number="3.2.1.5">
<h4 data-number="3.2.1.5" class="anchored" data-anchor-id="condiciones-de-segundo-orden"><span class="header-section-number">3.2.1.5</span> <strong>Condiciones de segundo orden</strong></h4>
<p>La matriz Hessiana es: <span class="math display">\[\frac{\partial^2 SSE}{\partial \boldsymbol{\beta} \partial \boldsymbol{\beta}^T} = 2\mathbf{X}^T\mathbf{X}\]</span></p>
<p>Como <span class="math inline">\(\mathbf{X}^T\mathbf{X}\)</span> es positiva definida (bajo el supuesto de rango completo), <span class="math inline">\(\hat{\boldsymbol{\beta}}\)</span> es efectivamente un mínimo global.</p>
</section>
</section>
<section id="propiedades-de-los-estimadores" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="propiedades-de-los-estimadores"><span class="header-section-number">3.2.2</span> Propiedades de los estimadores</h3>
<section id="teorema-de-gauss-markov" class="level4" data-number="3.2.2.1">
<h4 data-number="3.2.2.1" class="anchored" data-anchor-id="teorema-de-gauss-markov"><span class="header-section-number">3.2.2.1</span> <strong>Teorema de Gauss-Markov</strong></h4>
<p><strong>Enunciado</strong>: Bajo los supuestos 1-5, los estimadores de mínimos cuadrados <span class="math inline">\(\hat{\boldsymbol{\beta}}\)</span> son BLUE (Best Linear Unbiased Estimators).</p>
<p><strong>Demostración de insesgadez:</strong></p>
<p><span class="math display">\[\begin{align}
E[\hat{\boldsymbol{\beta}}] &amp;= E[(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{y}]\\
&amp;= E[(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T(\mathbf{X}\boldsymbol{\beta} + \boldsymbol{\varepsilon})]\\
&amp;= (\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{X}\boldsymbol{\beta} + (\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T E[\boldsymbol{\varepsilon}]\\
&amp;= \boldsymbol{\beta}
\end{align}\]</span></p>
<p><strong>Matriz de varianzas-covarianzas:</strong></p>
<p><span class="math display">\[\begin{align}
\text{Var}(\hat{\boldsymbol{\beta}}) &amp;= \text{Var}[(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{y}]\\
&amp;= (\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T \text{Var}(\mathbf{y}) \mathbf{X}(\mathbf{X}^T\mathbf{X})^{-1}\\
&amp;= (\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T (\sigma^2 \mathbf{I}_n) \mathbf{X}(\mathbf{X}^T\mathbf{X})^{-1}\\
&amp;= \sigma^2(\mathbf{X}^T\mathbf{X})^{-1}
\end{align}\]</span></p>
<p>Por tanto: <span class="math display">\[\boxed{\text{Var}(\hat{\boldsymbol{\beta}}) = \sigma^2(\mathbf{X}^T\mathbf{X})^{-1}}\]</span></p>
</section>
<section id="distribución-de-los-estimadores" class="level4" data-number="3.2.2.2">
<h4 data-number="3.2.2.2" class="anchored" data-anchor-id="distribución-de-los-estimadores"><span class="header-section-number">3.2.2.2</span> <strong>Distribución de los estimadores</strong></h4>
<p>Bajo el supuesto de normalidad:</p>
<p><span class="math display">\[\hat{\boldsymbol{\beta}} \sim N(\boldsymbol{\beta}, \sigma^2(\mathbf{X}^T\mathbf{X})^{-1})\]</span></p>
<p><strong>Corolario</strong>: Para cada coeficiente individual: <span class="math display">\[\hat{\beta}_j \sim N\left(\beta_j, \sigma^2 [(\mathbf{X}^T\mathbf{X})^{-1}]_{jj}\right)\]</span></p>
</section>
</section>
<section id="estimación-de-la-varianza-del-error" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="estimación-de-la-varianza-del-error"><span class="header-section-number">3.2.3</span> Estimación de la varianza del error</h3>
<section id="suma-de-cuadrados-de-errores" class="level4" data-number="3.2.3.1">
<h4 data-number="3.2.3.1" class="anchored" data-anchor-id="suma-de-cuadrados-de-errores"><span class="header-section-number">3.2.3.1</span> <strong>Suma de cuadrados de errores</strong></h4>
<p><span class="math display">\[SSE = \mathbf{e}^T\mathbf{e} = (\mathbf{y} - \mathbf{X}\hat{\boldsymbol{\beta}})^T(\mathbf{y} - \mathbf{X}\hat{\boldsymbol{\beta}})\]</span></p>
<p>Usando <span class="math inline">\(\hat{\mathbf{y}} = \mathbf{H}\mathbf{y}\)</span> y <span class="math inline">\(\mathbf{e} = (\mathbf{I}_n - \mathbf{H})\mathbf{y}\)</span>:</p>
<p><span class="math display">\[SSE = \mathbf{y}^T(\mathbf{I}_n - \mathbf{H})\mathbf{y}\]</span></p>
</section>
<section id="esperanza-de-sse" class="level4" data-number="3.2.3.2">
<h4 data-number="3.2.3.2" class="anchored" data-anchor-id="esperanza-de-sse"><span class="header-section-number">3.2.3.2</span> <strong>Esperanza de SSE</strong></h4>
<p><strong>Lema</strong>: <span class="math inline">\(E[\mathbf{y}^T\mathbf{A}\mathbf{y}] = \text{traza}(\mathbf{A}\boldsymbol{\Sigma}) + \boldsymbol{\mu}^T\mathbf{A}\boldsymbol{\mu}\)</span></p>
<p>Para nuestro caso, con <span class="math inline">\(\mathbf{A} = \mathbf{I}_n - \mathbf{H}\)</span>, <span class="math inline">\(\boldsymbol{\Sigma} = \sigma^2\mathbf{I}_n\)</span>, y <span class="math inline">\(\boldsymbol{\mu} = \mathbf{X}\boldsymbol{\beta}\)</span>:</p>
<p><span class="math display">\[\begin{align}
E[SSE] &amp;= \text{traza}[(\mathbf{I}_n - \mathbf{H})\sigma^2\mathbf{I}_n] + \boldsymbol{\beta}^T\mathbf{X}^T(\mathbf{I}_n - \mathbf{H})\mathbf{X}\boldsymbol{\beta}\\
&amp;= \sigma^2 \text{traza}(\mathbf{I}_n - \mathbf{H}) + 0\\
&amp;= \sigma^2 (n - p - 1)
\end{align}\]</span></p>
</section>
<section id="estimador-insesgado-de-σ²" class="level4" data-number="3.2.3.3">
<h4 data-number="3.2.3.3" class="anchored" data-anchor-id="estimador-insesgado-de-σ²"><span class="header-section-number">3.2.3.3</span> <strong>Estimador insesgado de σ²</strong></h4>
<p><span class="math display">\[\boxed{\hat{\sigma}^2 = \frac{SSE}{n - p - 1} = \frac{\mathbf{e}^T\mathbf{e}}{n - p - 1}}\]</span></p>
<p><strong>Distribución</strong>: Bajo normalidad, <span class="math display">\[\frac{SSE}{\sigma^2} \sim \chi^2_{n-p-1}\]</span></p>
</section>
<section id="error-estándar-de-los-coeficientes" class="level4" data-number="3.2.3.4">
<h4 data-number="3.2.3.4" class="anchored" data-anchor-id="error-estándar-de-los-coeficientes"><span class="header-section-number">3.2.3.4</span> <strong>Error estándar de los coeficientes</strong></h4>
<p><span class="math display">\[\text{se}(\hat{\beta}_j) = \sqrt{\hat{\sigma}^2 [(\mathbf{X}^T\mathbf{X})^{-1}]_{jj}}\]</span></p>
</section>
</section>
<section id="interpretación-de-coeficientes-en-regresión-múltiple" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="interpretación-de-coeficientes-en-regresión-múltiple"><span class="header-section-number">3.2.4</span> Interpretación de coeficientes en regresión múltiple</h3>
<section id="concepto-fundamental" class="level4" data-number="3.2.4.1">
<h4 data-number="3.2.4.1" class="anchored" data-anchor-id="concepto-fundamental"><span class="header-section-number">3.2.4.1</span> <strong>Concepto fundamental</strong></h4>
<p>En regresión múltiple, cada coeficiente <span class="math inline">\(\beta_j\)</span> representa:</p>
<blockquote class="blockquote">
<p><strong>El cambio esperado en <span class="math inline">\(Y\)</span> por unidad de cambio en <span class="math inline">\(X_j\)</span>, manteniendo todas las demás variables predictoras constantes.</strong></p>
</blockquote>
<p>Matemáticamente: <span class="math display">\[\beta_j = \frac{\partial E[Y|\mathbf{X}]}{\partial X_j}\]</span></p>
</section>
<section id="diferencia-con-correlaciones-simples" class="level4" data-number="3.2.4.2">
<h4 data-number="3.2.4.2" class="anchored" data-anchor-id="diferencia-con-correlaciones-simples"><span class="header-section-number">3.2.4.2</span> <strong>Diferencia con correlaciones simples</strong></h4>
<p>El coeficiente de regresión múltiple <span class="math inline">\(\hat{\beta}_j\)</span> es <strong>diferente</strong> del coeficiente de regresión simple de <span class="math inline">\(Y\)</span> sobre <span class="math inline">\(X_j\)</span>:</p>
<ul>
<li><strong>Regresión simple</strong>: <span class="math inline">\(\hat{\beta}_j^{(simple)} = \frac{\text{Cov}(Y, X_j)}{\text{Var}(X_j)}\)</span></li>
<li><strong>Regresión múltiple</strong>: <span class="math inline">\(\hat{\beta}_j\)</span> está “ajustado” por las demás variables</li>
</ul>
</section>
<section id="relación-con-correlaciones-parciales" class="level4" data-number="3.2.4.3">
<h4 data-number="3.2.4.3" class="anchored" data-anchor-id="relación-con-correlaciones-parciales"><span class="header-section-number">3.2.4.3</span> <strong>Relación con correlaciones parciales</strong></h4>
<p>El coeficiente de regresión múltiple está relacionado con la <strong>correlación parcial</strong>:</p>
<p><span class="math display">\[r_{Y,X_j|X_{-j}} = \text{corr}(Y, X_j | X_1, ..., X_{j-1}, X_{j+1}, ..., X_p)\]</span></p>
<p>Esta es la correlación entre <span class="math inline">\(Y\)</span> y <span class="math inline">\(X_j\)</span> después de eliminar el efecto de las demás variables.</p>
</section>
</section>
<section id="propiedades-de-los-residuos-y-valores-ajustados" class="level3" data-number="3.2.5">
<h3 data-number="3.2.5" class="anchored" data-anchor-id="propiedades-de-los-residuos-y-valores-ajustados"><span class="header-section-number">3.2.5</span> Propiedades de los residuos y valores ajustados</h3>
<section id="propiedades-de-los-residuos" class="level4" data-number="3.2.5.1">
<h4 data-number="3.2.5.1" class="anchored" data-anchor-id="propiedades-de-los-residuos"><span class="header-section-number">3.2.5.1</span> <strong>Propiedades de los residuos</strong></h4>
<p>Los residuos <span class="math inline">\(\mathbf{e} = \mathbf{y} - \hat{\mathbf{y}}\)</span> satisfacen:</p>
<ol type="1">
<li><strong>Suma cero</strong>: <span class="math inline">\(\sum_{i=1}^n e_i = \mathbf{1}^T\mathbf{e} = 0\)</span></li>
<li><strong>Ortogonalidad con predictores</strong>: <span class="math inline">\(\mathbf{X}^T\mathbf{e} = \mathbf{0}\)</span></li>
<li><strong>Ortogonalidad con valores ajustados</strong>: <span class="math inline">\(\hat{\mathbf{y}}^T\mathbf{e} = 0\)</span></li>
</ol>
</section>
<section id="propiedades-de-los-valores-ajustados" class="level4" data-number="3.2.5.2">
<h4 data-number="3.2.5.2" class="anchored" data-anchor-id="propiedades-de-los-valores-ajustados"><span class="header-section-number">3.2.5.2</span> <strong>Propiedades de los valores ajustados</strong></h4>
<p>Los valores ajustados <span class="math inline">\(\hat{\mathbf{y}} = \mathbf{X}\hat{\boldsymbol{\beta}}\)</span> satisfacen:</p>
<ol type="1">
<li><strong>Media</strong>: <span class="math inline">\(E[\hat{Y}_i] = E[Y_i] = \mathbf{x}_i^T\boldsymbol{\beta}\)</span></li>
<li><strong>Varianza</strong>: <span class="math inline">\(\text{Var}(\hat{Y}_i) = \sigma^2 \mathbf{h}_{ii}\)</span> donde <span class="math inline">\(\mathbf{h}_{ii} = \mathbf{x}_i^T(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{x}_i\)</span></li>
<li><strong>Covarianza con residuos</strong>: <span class="math inline">\(\text{Cov}(\hat{Y}_i, e_i) = 0\)</span></li>
</ol>
</section>
<section id="descomposición-de-varianza" class="level4" data-number="3.2.5.3">
<h4 data-number="3.2.5.3" class="anchored" data-anchor-id="descomposición-de-varianza"><span class="header-section-number">3.2.5.3</span> <strong>Descomposición de varianza</strong></h4>
<p><strong>Teorema de Pitágoras en regresión</strong>: <span class="math display">\[\|\mathbf{y}\|^2 = \|\hat{\mathbf{y}}\|^2 + \|\mathbf{e}\|^2\]</span></p>
<p>En términos de sumas de cuadrados: <span class="math display">\[\sum_{i=1}^n (Y_i - \bar{Y})^2 = \sum_{i=1}^n (\hat{Y}_i - \bar{Y})^2 + \sum_{i=1}^n e_i^2\]</span></p>
<p><span class="math display">\[\boxed{SST = SSR + SSE}\]</span></p>
<p>donde: - <span class="math inline">\(SST = \sum_{i=1}^n (Y_i - \bar{Y})^2\)</span> (suma total de cuadrados) - <span class="math inline">\(SSR = \sum_{i=1}^n (\hat{Y}_i - \bar{Y})^2\)</span> (suma de cuadrados de la regresión) - <span class="math inline">\(SSE = \sum_{i=1}^n e_i^2\)</span> (suma de cuadrados del error)</p>
</section>
</section>
<section id="inferencia-estadística" class="level3" data-number="3.2.6">
<h3 data-number="3.2.6" class="anchored" data-anchor-id="inferencia-estadística"><span class="header-section-number">3.2.6</span> Inferencia estadística</h3>
<section id="distribuciones-para-inferencia" class="level4" data-number="3.2.6.1">
<h4 data-number="3.2.6.1" class="anchored" data-anchor-id="distribuciones-para-inferencia"><span class="header-section-number">3.2.6.1</span> <strong>Distribuciones para inferencia</strong></h4>
<p>Bajo normalidad:</p>
<ol type="1">
<li><p><strong>Coeficientes individuales</strong>: <span class="math display">\[\frac{\hat{\beta}_j - \beta_j}{\text{se}(\hat{\beta}_j)} \sim t_{n-p-1}\]</span></p></li>
<li><p><strong>Combinaciones lineales</strong>: <span class="math display">\[\frac{\mathbf{c}^T\hat{\boldsymbol{\beta}} - \mathbf{c}^T\boldsymbol{\beta}}}{\sqrt{\hat{\sigma}^2 \mathbf{c}^T(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{c}}} \sim t_{n-p-1}\]</span></p></li>
<li><p><strong>Pruebas F</strong>: <span class="math display">\[\frac{(\mathbf{L}\hat{\boldsymbol{\beta}} - \mathbf{c})^T[\mathbf{L}(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{L}^T]^{-1}(\mathbf{L}\hat{\boldsymbol{\beta}} - \mathbf{c})/q}{\hat{\sigma}^2} \sim F_{q, n-p-1}\]</span></p></li>
</ol>
</section>
<section id="coeficiente-de-determinación-múltiple" class="level4" data-number="3.2.6.2">
<h4 data-number="3.2.6.2" class="anchored" data-anchor-id="coeficiente-de-determinación-múltiple"><span class="header-section-number">3.2.6.2</span> <strong>Coeficiente de determinación múltiple</strong></h4>
<p><span class="math display">\[R^2 = \frac{SSR}{SST} = 1 - \frac{SSE}{SST}\]</span></p>
<p><strong>Propiedades</strong>: - <span class="math inline">\(0 \leq R^2 \leq 1\)</span> - <span class="math inline">\(R^2\)</span> nunca decrece al agregar variables - <span class="math inline">\(R^2 = \text{corr}^2(\mathbf{y}, \hat{\mathbf{y}})\)</span></p>
<p><strong>R² ajustado</strong>: <span class="math display">\[R^2_{adj} = 1 - \frac{SSE/(n-p-1)}{SST/(n-1)} = 1 - \frac{\hat{\sigma}^2}{s_Y^2}\]</span></p>
<p>donde <span class="math inline">\(s_Y^2 = SST/(n-1)\)</span> es la varianza muestral de <span class="math inline">\(Y\)</span>.</p>
<ul>
<li><strong>Insesgadez</strong>: <span class="math inline">\(E[\hat{\boldsymbol{\beta}}] = \boldsymbol{\beta}\)</span></li>
<li><strong>Varianza mínima</strong>: Entre todos los estimadores lineales insesgados</li>
<li><strong>Matriz de varianzas-covarianzas</strong>: <span class="math inline">\(\text{Var}(\hat{\boldsymbol{\beta}}) = \sigma^2(\mathbf{X}^T\mathbf{X})^{-1}\)</span></li>
</ul>
</section>
</section>
</section>
<section id="sec-ejemplo-practico" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-ejemplo-practico"><span class="header-section-number">3.3</span> Ejemplo práctico: Datos de viviendas</h2>
<p>Vamos a desarrollar un ejemplo completo usando datos de precios de viviendas, que nos permitirá ilustrar todos los conceptos del capítulo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Configuración inicial</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(broom)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(car)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(corrplot)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(gridExtra)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear datos simulados realistas de precios de viviendas</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables predictoras</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>superficie <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="dv">120</span>, <span class="dv">30</span>)  <span class="co"># m2</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>habitaciones <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">2</span> <span class="sc">+</span> <span class="fl">0.02</span><span class="sc">*</span>superficie <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="fl">0.8</span>))  <span class="co"># número</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>antiguedad <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">50</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>)  <span class="co"># años</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>distancia_centro <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="dv">1</span>, <span class="dv">25</span>)  <span class="co"># km</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>garaje <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.6</span>)  <span class="co"># 0/1</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Variable respuesta con relaciones realistas</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>precio <span class="ot">&lt;-</span> <span class="dv">50000</span> <span class="sc">+</span> </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1200</span><span class="sc">*</span>superficie <span class="sc">+</span> </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  <span class="dv">15000</span><span class="sc">*</span>habitaciones <span class="sc">-</span> </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="dv">800</span><span class="sc">*</span>antiguedad <span class="sc">-</span> </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2000</span><span class="sc">*</span>distancia_centro <span class="sc">+</span> </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="dv">25000</span><span class="sc">*</span>garaje <span class="sc">+</span> </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">15000</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear data frame</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>viviendas <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">precio =</span> <span class="fu">round</span>(precio),</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">superficie =</span> <span class="fu">round</span>(superficie),</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">habitaciones =</span> <span class="fu">pmax</span>(<span class="dv">1</span>, habitaciones),  <span class="co"># mínimo 1 habitación</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">antiguedad =</span> antiguedad,</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">distancia_centro =</span> <span class="fu">round</span>(distancia_centro, <span class="dv">1</span>),</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">garaje =</span> <span class="fu">factor</span>(garaje, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Sí"</span>))</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar las primeras observaciones</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(viviendas)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  precio superficie habitaciones antiguedad distancia_centro garaje
1 220470        103            6         40             22.4     Sí
2 251863        113            5         11             13.9     Sí
3 304866        167            5          7             14.3     Sí
4 266265        122            5          6              7.6     No
5 264892        124            4         14             16.8     Sí
6 340875        171            5         18              6.8     Sí</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exploración inicial: matriz de correlaciones</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>viviendas_num <span class="ot">&lt;-</span> viviendas <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>garaje) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">garaje_num =</span> <span class="fu">as.numeric</span>(viviendas<span class="sc">$</span>garaje) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(viviendas_num)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">method =</span> <span class="st">"color"</span>, <span class="at">type =</span> <span class="st">"upper"</span>, </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">addCoef.col =</span> <span class="st">"black"</span>, <span class="at">tl.cex =</span> <span class="fl">0.8</span>, <span class="at">number.cex =</span> <span class="fl">0.8</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tema2_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Matriz de correlaciones entre variables numéricas del dataset de viviendas</figcaption>
</figure>
</div>
</div>
</div>
<section id="modelo-múltiple-inicial" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="modelo-múltiple-inicial"><span class="header-section-number">3.3.1</span> Modelo múltiple inicial</h3>
<p>Comenzamos ajustando un modelo que incluye todas las variables disponibles:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo múltiple completo</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>modelo_completo <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> superficie <span class="sc">+</span> habitaciones <span class="sc">+</span> antiguedad <span class="sc">+</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                      distancia_centro <span class="sc">+</span> garaje, <span class="at">data =</span> viviendas)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_completo)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = precio ~ superficie + habitaciones + antiguedad + 
    distancia_centro + garaje, data = viviendas)

Residuals:
   Min     1Q Median     3Q    Max 
-38847 -11074    867   9898  38486 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      53750.97    6666.71   8.063 7.53e-14 ***
superficie        1171.78      47.28  24.783  &lt; 2e-16 ***
habitaciones     15072.31    1303.42  11.564  &lt; 2e-16 ***
antiguedad        -744.59      75.42  -9.872  &lt; 2e-16 ***
distancia_centro -2028.27     164.88 -12.302  &lt; 2e-16 ***
garajeSí         25829.43    2349.44  10.994  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 15950 on 194 degrees of freedom
Multiple R-squared:  0.9094,    Adjusted R-squared:  0.9071 
F-statistic: 389.4 on 5 and 194 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="interpretación-de-coeficientes" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="interpretación-de-coeficientes"><span class="header-section-number">3.3.2</span> Interpretación de coeficientes</h3>
<p>Analicemos la interpretación de cada coeficiente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraer coeficientes con intervalos de confianza</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>coef_tabla <span class="ot">&lt;-</span> <span class="fu">tidy</span>(modelo_completo, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">estimate =</span> <span class="fu">round</span>(estimate, <span class="dv">0</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">std.error =</span> <span class="fu">round</span>(std.error, <span class="dv">0</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">conf.low =</span> <span class="fu">round</span>(conf.low, <span class="dv">0</span>),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">conf.high =</span> <span class="fu">round</span>(conf.high, <span class="dv">0</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(coef_tabla)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  term             estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)         53751      6667      8.06 7.53e-14    40602     66899
2 superficie           1172        47     24.8  5.05e-62     1079      1265
3 habitaciones        15072      1303     11.6  7.28e-24    12502     17643
4 antiguedad           -745        75     -9.87 6.96e-19     -893      -596
5 distancia_centro    -2028       165    -12.3  4.38e-26    -2353     -1703
6 garajeSí            25829      2349     11.0  3.64e-22    21196     30463</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong></p>
<ul>
<li><strong>Superficie</strong>: Por cada m² adicional, el precio aumenta en promedio 1172 euros, manteniendo constantes las demás variables.</li>
<li><strong>Habitaciones</strong>: Cada habitación adicional incrementa el precio en 1.5072^{4} euros en promedio, ceteris paribus.</li>
<li><strong>Antigüedad</strong>: Por cada año de antigüedad, el precio disminuye en 745 euros en promedio.</li>
<li><strong>Distancia al centro</strong>: Cada km adicional de distancia reduce el precio en 2028 euros en promedio.</li>
<li><strong>Garaje</strong>: Las viviendas con garaje cuestan 2.5829^{4} euros más que las que no tienen, en promedio.</li>
</ul>
</section>
</section>
<section id="sec-transformaciones-variables" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-transformaciones-variables"><span class="header-section-number">3.4</span> Transformaciones de variables</h2>
<p>Las transformaciones nos permiten capturar relaciones no lineales entre las variables manteniendo la estructura del modelo lineal. Las transformaciones más comunes incluyen logarítmicas, polinomiales, y de raíz cuadrada.</p>
<section id="transformación-logarítmica" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="transformación-logarítmica"><span class="header-section-number">3.4.1</span> Transformación logarítmica</h3>
<p>La transformación logarítmica es útil cuando esperamos efectos multiplicativos o cuando la variabilidad de la respuesta aumenta con su nivel:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo con transformación logarítmica del precio</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>modelo_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(precio) <span class="sc">~</span> superficie <span class="sc">+</span> habitaciones <span class="sc">+</span> antiguedad <span class="sc">+</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                 distancia_centro <span class="sc">+</span> garaje, <span class="at">data =</span> viviendas)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparación gráfica</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(viviendas, <span class="fu">aes</span>(<span class="at">x =</span> superficie, <span class="at">y =</span> precio)) <span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Modelo Lineal"</span>, <span class="at">y =</span> <span class="st">"Precio (euros)"</span>) <span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(viviendas, <span class="fu">aes</span>(<span class="at">x =</span> superficie, <span class="at">y =</span> <span class="fu">log</span>(precio))) <span class="sc">+</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Modelo Logarítmico"</span>, <span class="at">y =</span> <span class="st">"log(Precio)"</span>) <span class="sc">+</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tema2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Comparación entre modelo lineal y logarítmico para la relación precio-superficie</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="transformación-polinomial" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="transformación-polinomial"><span class="header-section-number">3.4.2</span> Transformación polinomial</h3>
<p>Los términos polinomiales capturan relaciones curvilíneas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo con término cuadrático para superficie</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>modelo_poly <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> superficie <span class="sc">+</span> <span class="fu">I</span>(superficie<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> habitaciones <span class="sc">+</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                  antiguedad <span class="sc">+</span> distancia_centro <span class="sc">+</span> garaje, <span class="at">data =</span> viviendas)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_poly)<span class="sc">$</span>coefficients</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Estimate   Std. Error    t value     Pr(&gt;|t|)
(Intercept)      74252.878310 16652.828772   4.458875 1.396227e-05
superficie         839.260675   252.054844   3.329675 1.041537e-03
I(superficie^2)      1.346415     1.002568   1.342966 1.808602e-01
habitaciones     14875.840462  1308.927329  11.364909 3.027053e-23
antiguedad        -756.980422    75.828449  -9.982802 3.475777e-19
distancia_centro -2023.469906   164.575995 -12.295049 4.924426e-26
garajeSí         25871.694763  2344.803353  11.033631 2.918623e-22</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualización del efecto polinomial</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>superficie_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(viviendas<span class="sc">$</span>superficie), <span class="fu">max</span>(viviendas<span class="sc">$</span>superficie), <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>pred_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">superficie =</span> superficie_seq,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">habitaciones =</span> <span class="fu">mean</span>(viviendas<span class="sc">$</span>habitaciones),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">antiguedad =</span> <span class="fu">mean</span>(viviendas<span class="sc">$</span>antiguedad),</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">distancia_centro =</span> <span class="fu">mean</span>(viviendas<span class="sc">$</span>distancia_centro),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">garaje =</span> <span class="st">"No"</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>pred_data<span class="sc">$</span>precio_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_poly, pred_data)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> viviendas, <span class="fu">aes</span>(<span class="at">x =</span> superficie, <span class="at">y =</span> precio), <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> pred_data, <span class="fu">aes</span>(<span class="at">x =</span> superficie, <span class="at">y =</span> precio_pred), </span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Modelo con término cuadrático"</span>,</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Superficie (m²)"</span>, <span class="at">y =</span> <span class="st">"Precio (euros)"</span>) <span class="sc">+</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tema2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Efecto cuadrático de la superficie sobre el precio</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="transformación-de-variables-predictoras" class="level3" data-number="3.4.3">
<h3 data-number="3.4.3" class="anchored" data-anchor-id="transformación-de-variables-predictoras"><span class="header-section-number">3.4.3</span> Transformación de variables predictoras</h3>
<p>También podemos transformar las variables predictoras:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo con transformación logarítmica de distancia</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>modelo_log_dist <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> superficie <span class="sc">+</span> habitaciones <span class="sc">+</span> antiguedad <span class="sc">+</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">log</span>(distancia_centro <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">+</span> garaje, <span class="at">data =</span> viviendas)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparar modelos</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo_completo, modelo_log, modelo_poly, modelo_log_dist)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                df       AIC
modelo_completo  7 4446.4114
modelo_log       7 -437.3369
modelo_poly      8 4446.5511
modelo_log_dist  7 4444.2773</code></pre>
</div>
</div>
</section>
</section>
<section id="sec-interacciones" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-interacciones"><span class="header-section-number">3.5</span> Interacciones entre variables</h2>
<p>Las interacciones permiten que el efecto de una variable predictora dependa del nivel de otra variable. Son especialmente importantes cuando las variables actúan de manera sinérgica.</p>
<section id="concepto-de-interacción" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="concepto-de-interacción"><span class="header-section-number">3.5.1</span> Concepto de interacción</h3>
<p>Una interacción entre <span class="math inline">\(X_1\)</span> y <span class="math inline">\(X_2\)</span> se modela como:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_1 X_2 + \varepsilon\]</span></p>
<p>El coeficiente <span class="math inline">\(\beta_3\)</span> representa el <strong>cambio adicional</strong> en el efecto de <span class="math inline">\(X_1\)</span> por unidad de cambio en <span class="math inline">\(X_2\)</span>.</p>
</section>
<section id="interacción-entre-variables-continuas" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="interacción-entre-variables-continuas"><span class="header-section-number">3.5.2</span> Interacción entre variables continuas</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo con interacción superficie × habitaciones</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>modelo_interaccion <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> superficie <span class="sc">*</span> habitaciones <span class="sc">+</span> antiguedad <span class="sc">+</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                         distancia_centro <span class="sc">+</span> garaje, <span class="at">data =</span> viviendas)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_interaccion)<span class="sc">$</span>coefficients</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            Estimate  Std. Error     t value     Pr(&gt;|t|)
(Intercept)             58325.380792 19200.37504   3.0377209 2.713560e-03
superficie               1133.070803   159.51279   7.1033227 2.284053e-11
habitaciones            14070.133606  4154.27818   3.3869021 8.565773e-04
antiguedad               -746.964052    76.17839  -9.8054581 1.126298e-18
distancia_centro        -2024.447507   165.96003 -12.1984039 9.626906e-26
garajeSí                25837.498774  2355.34152  10.9697463 4.511083e-22
superficie:habitaciones     8.248727    32.45790   0.2541362 7.996609e-01</code></pre>
</div>
</div>
</section>
<section id="interacción-entre-variable-continua-y-categórica" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="interacción-entre-variable-continua-y-categórica"><span class="header-section-number">3.5.3</span> Interacción entre variable continua y categórica</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo con interacción superficie × garaje</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>modelo_int_garaje <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> superficie <span class="sc">*</span> garaje <span class="sc">+</span> habitaciones <span class="sc">+</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                        antiguedad <span class="sc">+</span> distancia_centro, <span class="at">data =</span> viviendas)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_int_garaje)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = precio ~ superficie * garaje + habitaciones + antiguedad + 
    distancia_centro, data = viviendas)

Residuals:
   Min     1Q Median     3Q    Max 
-39256  -9688   1116  10185  38051 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         63328.67    9182.22   6.897  7.4e-11 ***
superficie           1093.31      70.12  15.593  &lt; 2e-16 ***
garajeSí            10987.33   10095.82   1.088    0.278    
habitaciones        15060.02    1299.15  11.592  &lt; 2e-16 ***
antiguedad           -751.04      75.29  -9.975  &lt; 2e-16 ***
distancia_centro    -2039.14     164.49 -12.397  &lt; 2e-16 ***
superficie:garajeSí   124.87      82.62   1.511    0.132    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 15900 on 193 degrees of freedom
Multiple R-squared:  0.9105,    Adjusted R-squared:  0.9077 
F-statistic: 327.1 on 6 and 193 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualización de la interacción</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(viviendas, <span class="fu">aes</span>(<span class="at">x =</span> superficie, <span class="at">y =</span> precio, <span class="at">color =</span> garaje)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">formula =</span> y <span class="sc">~</span> x) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Interacción Superficie × Garaje"</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Superficie (m²)"</span>, <span class="at">y =</span> <span class="st">"Precio (euros)"</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Garaje"</span>) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tema2_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Interacción entre superficie y presencia de garaje</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretación-de-interacciones" class="level3" data-number="3.5.4">
<h3 data-number="3.5.4" class="anchored" data-anchor-id="interpretación-de-interacciones"><span class="header-section-number">3.5.4</span> Interpretación de interacciones</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes del modelo con interacción</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>coef_int <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo_int_garaje)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(coef_int)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept)          superficie            garajeSí        habitaciones 
         63328.6747           1093.3102          10987.3343          15060.0232 
         antiguedad    distancia_centro superficie:garajeSí 
          -751.0361          -2039.1351            124.8714 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Interpretación de la interacción superficie × garaje:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Interpretación de la interacción superficie × garaje:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- Para viviendas SIN garaje: efecto de superficie ="</span>, <span class="fu">round</span>(coef_int[<span class="dv">2</span>], <span class="dv">0</span>), <span class="st">"euros/m²</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Para viviendas SIN garaje: efecto de superficie = 1093 euros/m²</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- Para viviendas CON garaje: efecto de superficie ="</span>, <span class="fu">round</span>(coef_int[<span class="dv">2</span>] <span class="sc">+</span> coef_int[<span class="dv">6</span>], <span class="dv">0</span>), <span class="st">"euros/m²</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Para viviendas CON garaje: efecto de superficie = -946 euros/m²</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- Diferencia en el efecto de superficie ="</span>, <span class="fu">round</span>(coef_int[<span class="dv">6</span>], <span class="dv">0</span>), <span class="st">"euros/m²</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Diferencia en el efecto de superficie = -2039 euros/m²</code></pre>
</div>
</div>
</section>
</section>
<section id="sec-diagnostico-multiple" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="sec-diagnostico-multiple"><span class="header-section-number">3.6</span> Diagnóstico del modelo múltiple</h2>
<p>El diagnóstico en regresión múltiple requiere técnicas específicas que van más allá de las utilizadas en regresión simple. Nos enfocaremos en los aspectos únicos del caso multivariante.</p>
<section id="gráficos-de-residuos-parciales" class="level3" data-number="3.6.1">
<h3 data-number="3.6.1" class="anchored" data-anchor-id="gráficos-de-residuos-parciales"><span class="header-section-number">3.6.1</span> Gráficos de residuos parciales</h3>
<p>Los gráficos de residuos parciales (added-variable plots) son específicos de regresión múltiple y ayudan a identificar la contribución individual de cada variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráficos de residuos parciales</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">avPlots</span>(modelo_completo, <span class="at">layout =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tema2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Gráficos de residuos parciales (Added-Variable Plots)</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="gráficos-de-residuos-vs-predictores" class="level3" data-number="3.6.2">
<h3 data-number="3.6.2" class="anchored" data-anchor-id="gráficos-de-residuos-vs-predictores"><span class="header-section-number">3.6.2</span> Gráficos de residuos vs predictores</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear gráficos de residuos vs cada predictor</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>residuos <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo_completo)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(viviendas, <span class="fu">aes</span>(<span class="at">x =</span> superficie, <span class="at">y =</span> residuos)) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuos vs Superficie"</span>) <span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(viviendas, <span class="fu">aes</span>(<span class="at">x =</span> habitaciones, <span class="at">y =</span> residuos)) <span class="sc">+</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuos vs Habitaciones"</span>) <span class="sc">+</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(viviendas, <span class="fu">aes</span>(<span class="at">x =</span> antiguedad, <span class="at">y =</span> residuos)) <span class="sc">+</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuos vs Antigüedad"</span>) <span class="sc">+</span></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(viviendas, <span class="fu">aes</span>(<span class="at">x =</span> distancia_centro, <span class="at">y =</span> residuos)) <span class="sc">+</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuos vs Distancia Centro"</span>) <span class="sc">+</span></span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, p3, p4, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
: pseudoinverse used at 4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
: neighborhood radius 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
: reciprocal condition number 0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
: There are other near singularities as well. 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tema2_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Residuos vs variables predictoras individuales</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="pruebas-estadísticas-específicas" class="level3" data-number="3.6.3">
<h3 data-number="3.6.3" class="anchored" data-anchor-id="pruebas-estadísticas-específicas"><span class="header-section-number">3.6.3</span> Pruebas estadísticas específicas</h3>
<p>Aplicamos las mismas pruebas que en regresión simple, pero interpretadas en el contexto multivariante:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultados de las pruebas</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"=== DIAGNÓSTICO DEL MODELO MÚLTIPLE ===</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== DIAGNÓSTICO DEL MODELO MÚLTIPLE ===</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"1. ESPECIFICACIÓN - Prueba RESET:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1. ESPECIFICACIÓN - Prueba RESET:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(reset_test)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  modelo_completo
RESET = 1.1755, df1 = 8, df2 = 186, p-value = 0.316</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Interpretación: p-valor"</span>, <span class="fu">ifelse</span>(reset_test<span class="sc">$</span>p.value <span class="sc">&gt;</span> <span class="fl">0.05</span>, <span class="st">"&gt;"</span>, <span class="st">"&lt;"</span>), </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"0.05 →"</span>, <span class="fu">ifelse</span>(reset_test<span class="sc">$</span>p.value <span class="sc">&gt;</span> <span class="fl">0.05</span>, <span class="st">"Modelo bien especificado"</span>, <span class="st">"Posible mala especificación"</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Interpretación: p-valor &gt; 0.05 → Modelo bien especificado </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"2. HOMOCEDASTICIDAD - Prueba Breusch-Pagan:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2. HOMOCEDASTICIDAD - Prueba Breusch-Pagan:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bp_test)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  modelo_completo
BP = 4.3836, df = 5, p-value = 0.4956</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Interpretación: p-valor"</span>, <span class="fu">ifelse</span>(bp_test<span class="sc">$</span>p.value <span class="sc">&gt;</span> <span class="fl">0.05</span>, <span class="st">"&gt;"</span>, <span class="st">"&lt;"</span>), </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"0.05 →"</span>, <span class="fu">ifelse</span>(bp_test<span class="sc">$</span>p.value <span class="sc">&gt;</span> <span class="fl">0.05</span>, <span class="st">"No hay heterocedasticidad"</span>, <span class="st">"Hay heterocedasticidad"</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Interpretación: p-valor &gt; 0.05 → No hay heterocedasticidad </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"3. NORMALIDAD - Prueba Shapiro-Wilk:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3. NORMALIDAD - Prueba Shapiro-Wilk:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sw_test)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(modelo_completo)
W = 0.99269, p-value = 0.4215</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Interpretación: p-valor"</span>, <span class="fu">ifelse</span>(sw_test<span class="sc">$</span>p.value <span class="sc">&gt;</span> <span class="fl">0.05</span>, <span class="st">"&gt;"</span>, <span class="st">"&lt;"</span>), </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"0.05 →"</span>, <span class="fu">ifelse</span>(sw_test<span class="sc">$</span>p.value <span class="sc">&gt;</span> <span class="fl">0.05</span>, <span class="st">"Residuos normales"</span>, <span class="st">"Residuos no normales"</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Interpretación: p-valor &gt; 0.05 → Residuos normales </code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"4. INDEPENDENCIA - Prueba Durbin-Watson:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>4. INDEPENDENCIA - Prueba Durbin-Watson:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(dw_test)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  modelo_completo
DW = 2.0477, p-value = 0.6355
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Interpretación: Estadístico ≈ 2 →"</span>, <span class="fu">ifelse</span>(<span class="fu">abs</span>(dw_test<span class="sc">$</span>statistic <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">&lt;</span> <span class="fl">0.5</span>, <span class="st">"Sin autocorrelación"</span>, <span class="st">"Posible autocorrelación"</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Interpretación: Estadístico ≈ 2 → Sin autocorrelación </code></pre>
</div>
</div>
</section>
</section>
<section id="sec-multicolinealidad" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="sec-multicolinealidad"><span class="header-section-number">3.7</span> Multicolinealidad</h2>
<p>La multicolinealidad es uno de los problemas más importantes y específicos de la regresión múltiple. Ocurre cuando existe una relación lineal fuerte entre dos o más variables predictoras.</p>
<section id="qué-es-la-multicolinealidad" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="qué-es-la-multicolinealidad"><span class="header-section-number">3.7.1</span> ¿Qué es la multicolinealidad?</h3>
<p>La multicolinealidad <strong>perfecta</strong> existe cuando una variable predictora es una combinación lineal exacta de otras variables predictoras. Más comúnmente, encontramos multicolinealidad <strong>imperfecta</strong>, donde existe una correlación alta pero no perfecta entre predictores.</p>
</section>
<section id="consecuencias-de-la-multicolinealidad" class="level3" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="consecuencias-de-la-multicolinealidad"><span class="header-section-number">3.7.2</span> Consecuencias de la multicolinealidad</h3>
<ol type="1">
<li><strong>Estimación inestable</strong>: Pequeños cambios en los datos pueden producir grandes cambios en los coeficientes</li>
<li><strong>Errores estándar inflados</strong>: Intervalos de confianza muy amplios</li>
<li><strong>Problemas de interpretación</strong>: Dificulta la interpretación de coeficientes individuales</li>
<li><strong>No afecta la predicción</strong>: El <span class="math inline">\(R^2\)</span> y las predicciones no se ven afectados</li>
</ol>
</section>
<section id="detección-factor-de-inflación-de-varianza-vif" class="level3" data-number="3.7.3">
<h3 data-number="3.7.3" class="anchored" data-anchor-id="detección-factor-de-inflación-de-varianza-vif"><span class="header-section-number">3.7.3</span> Detección: Factor de Inflación de Varianza (VIF)</h3>
<p>El VIF mide cuánto se infla la varianza de un coeficiente debido a la colinealidad:</p>
<p><span class="math display">\[VIF_j = \frac{1}{1 - R_j^2}\]</span></p>
<p>donde <span class="math inline">\(R_j^2\)</span> es el <span class="math inline">\(R^2\)</span> de la regresión de <span class="math inline">\(X_j\)</span> sobre las demás variables predictoras.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cálculo de VIF</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>vif_valores <span class="ot">&lt;-</span> <span class="fu">vif</span>(modelo_completo)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vif_valores)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      superficie     habitaciones       antiguedad distancia_centro 
        1.402428         1.399277         1.012659         1.005652 
          garaje 
        1.011321 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Interpretación de VIF:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Interpretación de VIF:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- VIF = 1: Sin multicolinealidad</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- VIF = 1: Sin multicolinealidad</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- 1 &lt; VIF &lt; 5: Multicolinealidad moderada</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- 1 &lt; VIF &lt; 5: Multicolinealidad moderada</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- VIF &gt; 5: Multicolinealidad problemática</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- VIF &gt; 5: Multicolinealidad problemática</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- VIF &gt; 10: Multicolinealidad severa</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- VIF &gt; 10: Multicolinealidad severa</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(vif_valores)) {</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  nivel <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(vif_valores[i] <span class="sc">&lt;</span> <span class="fl">1.5</span>, <span class="st">"Baja"</span>, </span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(vif_valores[i] <span class="sc">&lt;</span> <span class="dv">5</span>, <span class="st">"Moderada"</span>, </span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">ifelse</span>(vif_valores[i] <span class="sc">&lt;</span> <span class="dv">10</span>, <span class="st">"Problemática"</span>, <span class="st">"Severa"</span>)))</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="fu">names</span>(vif_valores)[i], <span class="st">": VIF ="</span>, <span class="fu">round</span>(vif_valores[i], <span class="dv">2</span>), <span class="st">"("</span>, nivel, <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>superficie : VIF = 1.4 ( Baja )
habitaciones : VIF = 1.4 ( Baja )
antiguedad : VIF = 1.01 ( Baja )
distancia_centro : VIF = 1.01 ( Baja )
garaje : VIF = 1.01 ( Baja )</code></pre>
</div>
</div>
</section>
<section id="ejemplo-de-multicolinealidad-alta" class="level3" data-number="3.7.4">
<h3 data-number="3.7.4" class="anchored" data-anchor-id="ejemplo-de-multicolinealidad-alta"><span class="header-section-number">3.7.4</span> Ejemplo de multicolinealidad alta</h3>
<p>Vamos a crear un ejemplo con multicolinealidad alta para ilustrar sus efectos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear variable altamente correlacionada con superficie</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>viviendas<span class="sc">$</span>superficie_alt <span class="ot">&lt;-</span> viviendas<span class="sc">$</span>superficie <span class="sc">*</span> <span class="fl">1.2</span> <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">5</span>)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo con multicolinealidad</span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>modelo_multicol <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> superficie <span class="sc">+</span> superficie_alt <span class="sc">+</span> habitaciones <span class="sc">+</span> </span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>                      antiguedad <span class="sc">+</span> distancia_centro <span class="sc">+</span> garaje, <span class="at">data =</span> viviendas)</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a><span class="co"># VIF del modelo con multicolinealidad</span></span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a>vif_multicol <span class="ot">&lt;-</span> <span class="fu">vif</span>(modelo_multicol)</span>
<span id="cb79-10"><a href="#cb79-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vif_multicol)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      superficie   superficie_alt     habitaciones       antiguedad 
       43.653595        43.062980         1.401020         1.016467 
distancia_centro           garaje 
        1.016017         1.011919 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparar errores estándar</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>se_original <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo_completo)<span class="sc">$</span>coefficients[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>se_multicol <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo_multicol)<span class="sc">$</span>coefficients[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Efecto en errores estándar:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Efecto en errores estándar:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- Error estándar superficie (modelo original):"</span>, <span class="fu">round</span>(se_original, <span class="dv">0</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Error estándar superficie (modelo original): 47 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- Error estándar superficie (con multicolinealidad):"</span>, <span class="fu">round</span>(se_multicol, <span class="dv">0</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Error estándar superficie (con multicolinealidad): 264 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- Incremento:"</span>, <span class="fu">round</span>((se_multicol<span class="sc">/</span>se_original <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Incremento: 457.6 %</code></pre>
</div>
</div>
</section>
<section id="soluciones-para-la-multicolinealidad" class="level3" data-number="3.7.5">
<h3 data-number="3.7.5" class="anchored" data-anchor-id="soluciones-para-la-multicolinealidad"><span class="header-section-number">3.7.5</span> Soluciones para la multicolinealidad</h3>
<ol type="1">
<li><strong>Eliminación de variables</strong>: Remover variables redundantes</li>
<li><strong>Combinación de variables</strong>: Crear índices o variables compuestas</li>
<li><strong>Regresión ridge o lasso</strong>: Técnicas de regularización (Tema 5)</li>
<li><strong>Análisis de componentes principales</strong>: Reducción de dimensionalidad</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ejemplo: eliminar variable redundante</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>modelo_sin_multicol <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> superficie <span class="sc">+</span> habitaciones <span class="sc">+</span> antiguedad <span class="sc">+</span> </span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>                          distancia_centro <span class="sc">+</span> garaje, <span class="at">data =</span> viviendas)</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparar VIF</span></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"VIF después de eliminar variable redundante:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>VIF después de eliminar variable redundante:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">vif</span>(modelo_sin_multicol))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      superficie     habitaciones       antiguedad distancia_centro 
        1.402428         1.399277         1.012659         1.005652 
          garaje 
        1.011321 </code></pre>
</div>
</div>
</section>
</section>
<section id="sec-evaluacion-modelos" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="sec-evaluacion-modelos"><span class="header-section-number">3.8</span> Evaluación y comparación de modelos</h2>
<section id="criterios-de-información" class="level3" data-number="3.8.1">
<h3 data-number="3.8.1" class="anchored" data-anchor-id="criterios-de-información"><span class="header-section-number">3.8.1</span> Criterios de información</h3>
<p>Los criterios de información nos ayudan a comparar modelos con diferentes números de parámetros:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparar diferentes modelos</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>modelos <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Completo"</span> <span class="ot">=</span> modelo_completo,</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Logarítmico"</span> <span class="ot">=</span> modelo_log,</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Polinomial"</span> <span class="ot">=</span> modelo_poly,</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Con interacción"</span> <span class="ot">=</span> modelo_int_garaje</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular criterios</span></span>
<span id="cb93-10"><a href="#cb93-10" aria-hidden="true" tabindex="-1"></a>criterios <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb93-11"><a href="#cb93-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Modelo =</span> <span class="fu">names</span>(modelos),</span>
<span id="cb93-12"><a href="#cb93-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">R2 =</span> <span class="fu">sapply</span>(modelos, <span class="cf">function</span>(m) <span class="fu">summary</span>(m)<span class="sc">$</span>r.squared),</span>
<span id="cb93-13"><a href="#cb93-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">R2_adj =</span> <span class="fu">sapply</span>(modelos, <span class="cf">function</span>(m) <span class="fu">summary</span>(m)<span class="sc">$</span>adj.r.squared),</span>
<span id="cb93-14"><a href="#cb93-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC =</span> <span class="fu">sapply</span>(modelos, AIC),</span>
<span id="cb93-15"><a href="#cb93-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">BIC =</span> <span class="fu">sapply</span>(modelos, BIC)</span>
<span id="cb93-16"><a href="#cb93-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb93-17"><a href="#cb93-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-18"><a href="#cb93-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Redondear solo las columnas numéricas</span></span>
<span id="cb93-19"><a href="#cb93-19" aria-hidden="true" tabindex="-1"></a>criterios[, <span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(criterios[, <span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], <span class="dv">4</span>)</span>
<span id="cb93-20"><a href="#cb93-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(criterios)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         Modelo     R2 R2_adj       AIC       BIC
Completo               Completo 0.9094 0.9071 4446.4114 4469.4996
Logarítmico         Logarítmico 0.8844 0.8814 -437.3369 -414.2486
Polinomial           Polinomial 0.9102 0.9074 4446.5511 4472.9376
Con interacción Con interacción 0.9105 0.9077 4446.0583 4472.4448</code></pre>
</div>
</div>
</section>
<section id="validación-cruzada" class="level3" data-number="3.8.2">
<h3 data-number="3.8.2" class="anchored" data-anchor-id="validación-cruzada"><span class="header-section-number">3.8.2</span> Validación cruzada</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Validación cruzada simple (división 80-20)</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">456</span>)</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>train_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(viviendas), <span class="fl">0.8</span> <span class="sc">*</span> <span class="fu">nrow</span>(viviendas))</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Datos de entrenamiento y prueba</span></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> viviendas[train_indices, ]</span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> viviendas[<span class="sc">-</span>train_indices, ]</span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo en datos de entrenamiento</span></span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a>modelo_train <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> superficie <span class="sc">+</span> habitaciones <span class="sc">+</span> antiguedad <span class="sc">+</span> </span>
<span id="cb95-11"><a href="#cb95-11" aria-hidden="true" tabindex="-1"></a>                   distancia_centro <span class="sc">+</span> garaje, <span class="at">data =</span> train_data)</span>
<span id="cb95-12"><a href="#cb95-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-13"><a href="#cb95-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicciones en datos de prueba</span></span>
<span id="cb95-14"><a href="#cb95-14" aria-hidden="true" tabindex="-1"></a>pred_test <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_train, test_data)</span>
<span id="cb95-15"><a href="#cb95-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-16"><a href="#cb95-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Error cuadrático medio de predicción</span></span>
<span id="cb95-17"><a href="#cb95-17" aria-hidden="true" tabindex="-1"></a>rmse_test <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test_data<span class="sc">$</span>precio <span class="sc">-</span> pred_test)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb95-18"><a href="#cb95-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-19"><a href="#cb95-19" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Error de predicción (RMSE):"</span>, <span class="fu">round</span>(rmse_test, <span class="dv">0</span>), <span class="st">"euros</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Error de predicción (RMSE): 17709 euros</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"RMSE como % del precio promedio:"</span>, <span class="fu">round</span>(rmse_test <span class="sc">/</span> <span class="fu">mean</span>(test_data<span class="sc">$</span>precio) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>RMSE como % del precio promedio: 7.6 %</code></pre>
</div>
</div>
</section>
</section>
<section id="sec-casos-especiales" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="sec-casos-especiales"><span class="header-section-number">3.9</span> Análisis de casos especiales</h2>
<section id="variables-categóricas-con-múltiples-niveles" class="level3" data-number="3.9.1">
<h3 data-number="3.9.1" class="anchored" data-anchor-id="variables-categóricas-con-múltiples-niveles"><span class="header-section-number">3.9.1</span> Variables categóricas con múltiples niveles</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear variable categórica con múltiples niveles</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>viviendas<span class="sc">$</span>zona <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Centro"</span>, <span class="st">"Norte"</span>, <span class="st">"Sur"</span>, <span class="st">"Este"</span>, <span class="st">"Oeste"</span>), </span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">nrow</span>(viviendas), <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo con variable categórica</span></span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>modelo_zona <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> superficie <span class="sc">+</span> habitaciones <span class="sc">+</span> antiguedad <span class="sc">+</span> </span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a>                  distancia_centro <span class="sc">+</span> garaje <span class="sc">+</span> zona, <span class="at">data =</span> viviendas)</span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen del modelo</span></span>
<span id="cb99-10"><a href="#cb99-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_zona)<span class="sc">$</span>coefficients</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Estimate Std. Error     t value     Pr(&gt;|t|)
(Intercept)      52411.4202 7175.74966   7.3039644 7.478269e-12
superficie        1167.9854   48.16096  24.2517054 4.496580e-60
habitaciones     15127.3702 1320.55427  11.4553188 1.940724e-23
antiguedad        -737.4404   76.31910  -9.6625927 3.215025e-18
distancia_centro -2029.8924  167.93012 -12.0877205 2.543815e-25
garajeSí         25974.4931 2374.86418  10.9372541 6.566663e-22
zonaEste          2753.8858 3478.82380   0.7916141 4.295729e-01
zonaNorte         1120.5041 3354.18628   0.3340614 7.387017e-01
zonaOeste         2843.0595 3550.67950   0.8007086 4.243005e-01
zonaSur           -229.8057 3904.68726  -0.0588538 9.531304e-01</code></pre>
</div>
</div>
</section>
<section id="análisis-de-outliers-en-regresión-múltiple" class="level3" data-number="3.9.2">
<h3 data-number="3.9.2" class="anchored" data-anchor-id="análisis-de-outliers-en-regresión-múltiple"><span class="header-section-number">3.9.2</span> Análisis de outliers en regresión múltiple</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar observaciones influyentes</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>influence_measures <span class="ot">&lt;-</span> <span class="fu">influence.measures</span>(modelo_completo)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in abbreviate(vn): abbreviate used with non-ASCII chars</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráficos de diagnóstico específicos para regresión múltiple</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_completo, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tema2_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Diagnóstico de observaciones influyentes en regresión múltiple</figcaption>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="sec-ejemplo-completo" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="sec-ejemplo-completo"><span class="header-section-number">3.10</span> Ejemplo completo: Análisis paso a paso</h2>
<p>Vamos a realizar un análisis completo desde el inicio, aplicando todo lo aprendido:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === PASO 1: EXPLORACIÓN INICIAL ===</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"=== ANÁLISIS EXPLORATORIO ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== ANÁLISIS EXPLORATORIO ===</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Dimensiones del dataset:"</span>, <span class="fu">dim</span>(viviendas)[<span class="dv">1</span>], <span class="st">"observaciones,"</span>, <span class="fu">dim</span>(viviendas)[<span class="dv">2</span>], <span class="st">"variables</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dimensiones del dataset: 200 observaciones, 8 variables</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estadísticas descriptivas</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(viviendas))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     precio         superficie     habitaciones    antiguedad   
 Min.   :111594   Min.   : 51.0   Min.   :2.00   Min.   : 0.00  
 1st Qu.:195075   1st Qu.:101.0   1st Qu.:4.00   1st Qu.: 9.00  
 Median :230604   Median :118.0   Median :4.00   Median :22.00  
 Mean   :233236   Mean   :119.7   Mean   :4.39   Mean   :23.45  
 3rd Qu.:266268   3rd Qu.:137.2   3rd Qu.:5.00   3rd Qu.:37.00  
 Max.   :370939   Max.   :217.0   Max.   :7.00   Max.   :50.00  
 distancia_centro garaje   superficie_alt       zona   
 Min.   : 1.10    No: 74   Min.   : 54.44   Centro:47  
 1st Qu.: 6.80    Sí:126   1st Qu.:121.67   Este  :40  
 Median :12.75             Median :142.97   Norte :48  
 Mean   :12.72             Mean   :143.81   Oeste :37  
 3rd Qu.:18.55             3rd Qu.:165.28   Sur   :28  
 Max.   :25.00             Max.   :251.66              </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === PASO 2: MODELO INICIAL ===</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>modelo_inicial <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> superficie <span class="sc">+</span> habitaciones <span class="sc">+</span> antiguedad <span class="sc">+</span> </span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>                     distancia_centro <span class="sc">+</span> garaje, <span class="at">data =</span> viviendas)</span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">=== MODELO INICIAL ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== MODELO INICIAL ===</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(modelo_inicial))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = precio ~ superficie + habitaciones + antiguedad + 
    distancia_centro + garaje, data = viviendas)

Residuals:
   Min     1Q Median     3Q    Max 
-38847 -11074    867   9898  38486 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      53750.97    6666.71   8.063 7.53e-14 ***
superficie        1171.78      47.28  24.783  &lt; 2e-16 ***
habitaciones     15072.31    1303.42  11.564  &lt; 2e-16 ***
antiguedad        -744.59      75.42  -9.872  &lt; 2e-16 ***
distancia_centro -2028.27     164.88 -12.302  &lt; 2e-16 ***
garajeSí         25829.43    2349.44  10.994  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 15950 on 194 degrees of freedom
Multiple R-squared:  0.9094,    Adjusted R-squared:  0.9071 
F-statistic: 389.4 on 5 and 194 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === PASO 3: DIAGNÓSTICO ===</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">=== DIAGNÓSTICO DEL MODELO ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== DIAGNÓSTICO DEL MODELO ===</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co"># VIF</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Factor de Inflación de Varianza (VIF):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Factor de Inflación de Varianza (VIF):</code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(<span class="fu">vif</span>(modelo_inicial), <span class="dv">2</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      superficie     habitaciones       antiguedad distancia_centro 
            1.40             1.40             1.01             1.01 
          garaje 
            1.01 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pruebas estadísticas silenciosas</span></span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>bp_final <span class="ot">&lt;-</span> <span class="fu">bptest</span>(modelo_inicial)</span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a>sw_final <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(modelo_inicial))</span>
<span id="cb121-4"><a href="#cb121-4" aria-hidden="true" tabindex="-1"></a>reset_final <span class="ot">&lt;-</span> <span class="fu">resettest</span>(modelo_inicial, <span class="at">power =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">type =</span> <span class="st">"regressor"</span>)</span>
<span id="cb121-5"><a href="#cb121-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-6"><a href="#cb121-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Pruebas de diagnóstico:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Pruebas de diagnóstico:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- Breusch-Pagan (homocedasticidad): p ="</span>, <span class="fu">round</span>(bp_final<span class="sc">$</span>p.value, <span class="dv">4</span>), </span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(bp_final<span class="sc">$</span>p.value <span class="sc">&gt;</span> <span class="fl">0.05</span>, <span class="st">" ✓"</span>, <span class="st">" ✗"</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Breusch-Pagan (homocedasticidad): p = 0.4956  ✓ </code></pre>
</div>
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- Shapiro-Wilk (normalidad): p ="</span>, <span class="fu">round</span>(sw_final<span class="sc">$</span>p.value, <span class="dv">4</span>), </span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(sw_final<span class="sc">$</span>p.value <span class="sc">&gt;</span> <span class="fl">0.05</span>, <span class="st">" ✓"</span>, <span class="st">" ✗"</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Shapiro-Wilk (normalidad): p = 0.4215  ✓ </code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- RESET (especificación): p ="</span>, <span class="fu">round</span>(reset_final<span class="sc">$</span>p.value, <span class="dv">4</span>), </span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(reset_final<span class="sc">$</span>p.value <span class="sc">&gt;</span> <span class="fl">0.05</span>, <span class="st">" ✓"</span>, <span class="st">" ✗"</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- RESET (especificación): p = 0.316  ✓ </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === PASO 4: MODELO FINAL CON MEJORAS ===</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Basándonos en el diagnóstico, podríamos mejorar el modelo</span></span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a>modelo_final <span class="ot">&lt;-</span> modelo_inicial  <span class="co"># En este caso, el modelo inicial es bueno</span></span>
<span id="cb129-4"><a href="#cb129-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-5"><a href="#cb129-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">=== RESUMEN FINAL ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== RESUMEN FINAL ===</code></pre>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"R² ="</span>, <span class="fu">round</span>(<span class="fu">summary</span>(modelo_final)<span class="sc">$</span>r.squared, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R² = 0.9094 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"R² ajustado ="</span>, <span class="fu">round</span>(<span class="fu">summary</span>(modelo_final)<span class="sc">$</span>adj.r.squared, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R² ajustado = 0.9071 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Error estándar residual ="</span>, <span class="fu">round</span>(<span class="fu">summary</span>(modelo_final)<span class="sc">$</span>sigma, <span class="dv">0</span>), <span class="st">"euros</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Error estándar residual = 15952 euros</code></pre>
</div>
</div>
</section>
<section id="sec-conclusiones" class="level2" data-number="3.11">
<h2 data-number="3.11" class="anchored" data-anchor-id="sec-conclusiones"><span class="header-section-number">3.11</span> Conclusiones y recomendaciones prácticas</h2>
<section id="puntos-clave-de-la-regresión-múltiple" class="level3" data-number="3.11.1">
<h3 data-number="3.11.1" class="anchored" data-anchor-id="puntos-clave-de-la-regresión-múltiple"><span class="header-section-number">3.11.1</span> Puntos clave de la regresión múltiple</h3>
<ol type="1">
<li><p><strong>Interpretación condicional</strong>: Los coeficientes deben interpretarse manteniendo las demás variables constantes.</p></li>
<li><p><strong>Multicolinealidad</strong>: Es el problema más específico de regresión múltiple. Use VIF &gt; 5 como señal de alarma.</p></li>
<li><p><strong>Transformaciones</strong>: Son herramientas poderosas para capturar relaciones no lineales manteniendo la interpretabilidad.</p></li>
<li><p><strong>Interacciones</strong>: Considere interacciones cuando tenga razones teóricas o empíricas para esperarlas.</p></li>
<li><p><strong>Diagnóstico específico</strong>: Use gráficos de residuos parciales y pruebas específicas para el caso multivariante.</p></li>
</ol>
</section>
<section id="flujo-de-trabajo-recomendado" class="level3" data-number="3.11.2">
<h3 data-number="3.11.2" class="anchored" data-anchor-id="flujo-de-trabajo-recomendado"><span class="header-section-number">3.11.2</span> Flujo de trabajo recomendado</h3>
<ol type="1">
<li><strong>Exploración</strong>: Analice correlaciones y distribuciones</li>
<li><strong>Modelo base</strong>: Comience con efectos principales</li>
<li><strong>Diagnóstico</strong>: Verifique supuestos y multicolinealidad</li>
<li><strong>Refinamiento</strong>: Considere transformaciones e interacciones</li>
<li><strong>Validación</strong>: Use validación cruzada para evaluar poder predictivo</li>
<li><strong>Interpretación</strong>: Comunique resultados de manera clara y contextualizada</li>
</ol>
</section>
<section id="preparación-para-temas-avanzados" class="level3" data-number="3.11.3">
<h3 data-number="3.11.3" class="anchored" data-anchor-id="preparación-para-temas-avanzados"><span class="header-section-number">3.11.3</span> Preparación para temas avanzados</h3>
<p>Los conceptos de este capítulo son fundamentales para: - <strong>Selección de variables</strong> (Tema 3): Decidir qué variables incluir - <strong>GLM</strong> (Tema 4): Extensión a variables respuesta no normales - <strong>Técnicas modernas</strong> (Tema 5): Regularización y métodos no paramétricos</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Buenas prácticas">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Buenas prácticas
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Siempre verifique VIF antes de interpretar coeficientes</li>
<li>Use gráficos de residuos parciales para evaluar la contribución individual de cada variable</li>
<li>Considere la interpretabilidad vs.&nbsp;capacidad predictiva según sus objetivos</li>
<li>Documente todas las decisiones de modelado para reproducibilidad</li>
<li>Valide siempre en datos independientes cuando sea posible</li>
</ul>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-draper1998applied" class="csl-entry" role="listitem">
Draper, NR. 1998. <em>Applied regression analysis</em>. McGraw-Hill. Inc.
</div>
<div id="ref-fox2018r" class="csl-entry" role="listitem">
Fox, John, y Sanford Weisberg. 2018. <em>An R companion to applied regression</em>. Sage publications.
</div>
<div id="ref-harrell2015" class="csl-entry" role="listitem">
Harrell, Frank E., Jr. 2015. <em>Regression Modeling Strategies: With Applications to Linear Models, Logistic and Ordinal Regression, and Survival Analysis</em>. Second. Springer.
</div>
<div id="ref-james2021" class="csl-entry" role="listitem">
James, Gareth, Daniela Witten, Trevor Hastie, y Robert Tibshirani. 2021. <em>An Introduction to Statistical Learning with Applications in R</em>. Second. Springer.
</div>
<div id="ref-kutner2005applied" class="csl-entry" role="listitem">
Kutner, Michael H, Christopher J Nachtsheim, John Neter, y William Li. 2005. <em>Applied linear statistical models</em>. McGraw-hill.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./tema1.html" class="pagination-link" aria-label="El modelo de regresión lineal simple">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">El modelo de regresión lineal simple</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./tema3.html" class="pagination-link" aria-label="Modelos no lineales. Transformación de variables. Ingeniería de características.">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelos no lineales. Transformación de variables. Ingeniería de características.</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>